/* eslint:disable */
/*
 * This file is automatically generated by SOT
 *
 * This file is for typings support only, it will not supply the actual text, you will still need to download the correct culture spesific .resx file.
 */
export type HNDesignsystemDropdown = {
  /**
   * Lukk
   */
  closeText: string;
};

export type HNDesignsystemPanel = {
  /**
   * Se detaljer
   */
  expandButtonOpen: string;
  /**
   * Skjul detaljer
   */
  expandButtonClose: string;
};

export type HNDesignsystemClose = {
  /**
   * Lukk
   */
  ariaLabel: string;
};

export type HNDesignsystemInfoTeaser = {
  /**
   * Vis mindre
   */
  expandButtonOpen: string;
  /**
   * Vis mer
   */
  expandButtonClose: string;
};

export type HNDesignsystemArticleTeaser = {
  /**
   * Vis mer
   */
  expandButtonClose: string;
  /**
   * Vis mindre
   */
  expandButtonOpen: string;
};

export type HNDesignsystemHelpBubble = {
  /**
   * Hjelpetekst
   */
  ariaLabel: string;
};

export type HNDesignsystemHelpDrawer = {
  /**
   * Hjelpetekst
   */
  ariaLabel: string;
};

export type HNDesignsystemFavoriteButton = {
  /**
   * Favorittmarkering
   */
  ariaLabel: string;
};

export type HNDesignsystemTabs = {
  /**
   * Scroll til høyre
   */
  ariaLabelRightButton: string;
  /**
   * Scroll til venstre
   */
  ariaLabelLeftButton: string;
};

export type HNDesignsystemDrawer = {
  /**
   * Lukk
   */
  ariaLabelCloseBtn: string;
};

export type HNDesignsystemFormFieldTag = {
  /**
   * Alle felt må fylles ut
   */
  allRequired: string;
  /**
   * Må fylles ut
   */
  requiredField: string;
  /**
   * Valgfritt
   */
  optional: string;
};

/* eslint:enable */
