/* eslint:disable */
/*
 * This file is automatically generated by SOT
 *
 * This file is for typings support only, it will not supply the actual text, you will still need to download the correct culture spesific .resx file.
 */
export type HNDesignsystemDropdown = {
  /**
   * Lukk
   */
  closeText: string;
};

export type HNDesignsystemPanel = {
  /**
   * Se detaljer
   */
  expandButtonOpen: string;
  /**
   * Skjul detaljer
   */
  expandButtonClose: string;
};

export type HNDesignsystemClose = {
  /**
   * Lukk
   */
  ariaLabel: string;
};

export type HNDesignsystemInfoTeaser = {
  /**
   * Vis mindre
   */
  expandButtonOpen: string;
  /**
   * Vis mer
   */
  expandButtonClose: string;
};

export type HNDesignsystemArticleTeaser = {
  /**
   * Vis mer
   */
  expandButtonClose: string;
  /**
   * Vis mindre
   */
  expandButtonOpen: string;
};

export type HNDesignsystemHelpBubble = {
  /**
   * Hjelpetekst
   */
  ariaLabel: string;
};

export type HNDesignsystemHelpDrawer = {
  /**
   * Hjelpetekst
   */
  ariaLabel: string;
};

export type HNDesignsystemFavoriteButton = {
  /**
   * Favorittmarkering
   */
  ariaLabel: string;
};

export type HNDesignsystemTabs = {
  /**
   * Scroll til høyre
   */
  ariaLabelRightButton: string;
  /**
   * Scroll til venstre
   */
  ariaLabelLeftButton: string;
};

export type HNDesignsystemDatePicker = {
  /**
   * Åpne datovelger
   */
  dateButtonAriaLabel: string;
  /**
   * Standard tekst for {date}
   */
  dayButtonBase: string;
  /**
   * I dag, {date}
   */
  dayButtonToday: string;
  /**
   * {date}, valgt
   */
  dayButtonSelected: string;
  /**
   * Neste måned
   */
  nextMonth: string;
  /**
   * Forrige måned
   */
  previousMonth: string;
  /**
   * Velg måned
   */
  monthDropdown: string;
  /**
   * Velg år
   */
  yearDropdown: string;
};

/* eslint:enable */
