/* eslint:disable */
/*
 * This file is automatically generated by SOT
 *
 * This file is for typings support only, it will not supply the actual text, you will still need to download the correct culture spesific .resx file.
 */
export type HNDesignsystemDropdown = {
  /**
   * Lukk
   */
  closeText: string;
};

export type HNDesignsystemPanel = {
  /**
   * Se detaljer
   */
  expandButtonOpen: string;
  /**
   * Skjul detaljerr
   */
  expandButtonClose: string;
};

export type HNDesignsystemClose = {
  /**
   * Lukk
   */
  ariaLabel: string;
};

/* eslint:enable */
