export type Styles = {
  'expander-list': string;
  'expander-list__item': string;
  'expander-list__item--fill': string;
  'expander-list__item--fill--blueberry': string;
  'expander-list__item--fill--cherry': string;
  'expander-list__item--fill--neutral': string;
  'expander-list__item--fill--white': string;
  'expander-list__item--fill-negative': string;
  'expander-list__item--line': string;
  'expander-list__item--line--blueberry': string;
  'expander-list__item--line--cherry': string;
  'expander-list__item--line--neutral': string;
  'expander-list__item--line--white': string;
  'expander-list__item--outline': string;
  'expander-list__item--outline--blueberry': string;
  'expander-list__item--outline--cherry': string;
  'expander-list__item--outline--neutral': string;
  'expander-list__item--outline--white': string;
  'expander-list-link': string;
  'expander-list-link__chevron': string;
  'expander-list-link__icon': string;
  'expander-list-link__main-content': string;
  'expander-list-link__main-content--expanded': string;
  'expander-list-link__main-content--padding': string;
  'expander-list-link--blueberry': string;
  'expander-list-link--cherry': string;
  'expander-list-link--closed': string;
  'expander-list-link--fill': string;
  'expander-list-link--fill--blueberry': string;
  'expander-list-link--fill--cherry': string;
  'expander-list-link--fill--neutral': string;
  'expander-list-link--fill--white': string;
  'expander-list-link--fill-negative': string;
  'expander-list-link--large': string;
  'expander-list-link--line--blueberry': string;
  'expander-list-link--line--cherry': string;
  'expander-list-link--line--neutral': string;
  'expander-list-link--line--white': string;
  'expander-list-link--neutral': string;
  'expander-list-link--open': string;
  'expander-list-link--outline': string;
  'expander-list-link--outline--blueberry': string;
  'expander-list-link--outline--cherry': string;
  'expander-list-link--outline--neutral': string;
  'expander-list-link--outline--white': string;
  'expander-list-link--white': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
