export type Styles = {
  'expander-list': string;
  'expander-list__item': string;
  'expander-list__item__status-marker': string;
  'expander-list__item__status-marker--new': string;
  'expander-list__item--fill': string;
  'expander-list__item--fill--blueberry': string;
  'expander-list__item--fill--cherry': string;
  'expander-list__item--fill--neutral': string;
  'expander-list__item--fill--white': string;
  'expander-list__item--fill-negative': string;
  'expander-list__item--fill-negative--blueberry': string;
  'expander-list__item--fill-negative--cherry': string;
  'expander-list__item--fill-negative--neutral': string;
  'expander-list__item--fill-negative--white': string;
  'expander-list__item--line': string;
  'expander-list__item--line--blueberry': string;
  'expander-list__item--line--cherry': string;
  'expander-list__item--line--neutral': string;
  'expander-list__item--line--white': string;
  'expander-list__item--new': string;
  'expander-list__item--outline': string;
  'expander-list__item--outline--blueberry': string;
  'expander-list__item--outline--cherry': string;
  'expander-list__item--outline--neutral': string;
  'expander-list__item--outline--white': string;
  'expander-list--fill': string;
  'expander-list--outline--blueberry': string;
  'expander-list--outline--cherry': string;
  'expander-list--outline--neutral': string;
  'expander-list--outline--white': string;
  'expander-list-link': string;
  'expander-list-link__chevron': string;
  'expander-list-link__icon': string;
  'expander-list-link__main-content': string;
  'expander-list-link__main-content--expanded': string;
  'expander-list-link__main-content--new': string;
  'expander-list-link__main-content--outline--blueberry': string;
  'expander-list-link__main-content--outline--cherry': string;
  'expander-list-link__main-content--outline--neutral': string;
  'expander-list-link__main-content--outline--white': string;
  'expander-list-link__main-content--padding': string;
  'expander-list-link--blueberry': string;
  'expander-list-link--cherry': string;
  'expander-list-link--fill--blueberry': string;
  'expander-list-link--fill--cherry': string;
  'expander-list-link--fill--neutral': string;
  'expander-list-link--fill--white': string;
  'expander-list-link--fill-negative': string;
  'expander-list-link--fill-negative--blueberry': string;
  'expander-list-link--fill-negative--cherry': string;
  'expander-list-link--fill-negative--neutral': string;
  'expander-list-link--fill-negative--white': string;
  'expander-list-link--large': string;
  'expander-list-link--line--blueberry': string;
  'expander-list-link--line--cherry': string;
  'expander-list-link--line--neutral': string;
  'expander-list-link--line--white': string;
  'expander-list-link--neutral': string;
  'expander-list-link--new': string;
  'expander-list-link--open': string;
  'expander-list-link--outline': string;
  'expander-list-link--outline--blueberry': string;
  'expander-list-link--outline--cherry': string;
  'expander-list-link--outline--neutral': string;
  'expander-list-link--outline--white': string;
  'expander-list-link--white': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
