
trigger: 
  - develop

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Installing and using NodeJS 10'
  - script: yarn install
    displayName: 'Installing dependencies'
  - script: yarn build
  - script: yarn test
  - task: CopyFiles@2
    displayName: 'Copying core files'
    inputs:
      Contents: |
        **/*
        !node_modules/
        !coverage/
        !types/
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Component Library'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: $(Build.Repository.Name)-$(Build.BuildNumber)-$(Build.SourceBranchName)