export type Styles = {
  'datetime-container': string;
  'datetime-container__icon': string;
  'header-container': string;
  panel: string;
  panel__badge: string;
  'panel__btn-container': string;
  'panel__btn-container--no-button': string;
  'panel__btn-container--no-content-b': string;
  'panel__details-btn': string;
  panel__expand: string;
  panel__icon: string;
  'panel__icon--layout-1': string;
  'panel__icon--layout-2': string;
  'panel__icon--layout-3': string;
  'panel__icon--no-content': string;
  'panel__layout-1': string;
  'panel__layout-1__content-a': string;
  'panel__layout-1--with-icon': string;
  'panel__layout-2': string;
  'panel__layout-2__content-a': string;
  'panel__layout-2__last-column': string;
  'panel__layout-2--with-icon': string;
  'panel__layout-3': string;
  'panel__layout-3__last-column': string;
  'panel__layout-3__last-column__content-b': string;
  'panel__layout-3--a': string;
  'panel__layout-3--b': string;
  'panel__layout-3--c': string;
  'panel__layout-3--with-icon': string;
  'panel--button': string;
  'panel--clickable': string;
  'panel--draft': string;
  'panel--error': string;
  'panel--fill': string;
  'panel--line': string;
  'panel--new': string;
  'panel--no-top-border': string;
  'panel--selected': string;
  'panel--status': string;
  'panel--stroke': string;
  'panel--white': string;
  'panel--with-icon': string;
  'panel-details': string;
  'panel-details--line': string;
  'panel-details--open': string;
  'panel-details--white': string;
  'panel-wrapper': string;
  'status-message': string;
  'status-message--new': string;
  'title-container': string;
  'title-container__title': string;
  'title-container__title--badge': string;
  'title-container--no-content-a': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
