import ActiveMonitoring_ from '@helsenorge/designsystem-react/components/Icons/ActiveMonitoring';
export const ActiveMonitoring = ActiveMonitoring_;
import AcupunctureBack_ from '@helsenorge/designsystem-react/components/Icons/AcupunctureBack';
export const AcupunctureBack = AcupunctureBack_;
import AlarmClock_ from '@helsenorge/designsystem-react/components/Icons/AlarmClock';
export const AlarmClock = AlarmClock_;
import AlertSignFill_ from '@helsenorge/designsystem-react/components/Icons/AlertSignFill';
export const AlertSignFill = AlertSignFill_;
import AlertSignStroke_ from '@helsenorge/designsystem-react/components/Icons/AlertSignStroke';
export const AlertSignStroke = AlertSignStroke_;
import Amputation_ from '@helsenorge/designsystem-react/components/Icons/Amputation';
export const Amputation = Amputation_;
import Anxiety_ from '@helsenorge/designsystem-react/components/Icons/Anxiety';
export const Anxiety = Anxiety_;
import Apple_ from '@helsenorge/designsystem-react/components/Icons/Apple';
export const Apple = Apple_;
import Archive_ from '@helsenorge/designsystem-react/components/Icons/Archive';
export const Archive = Archive_;
import ArmFlexing_ from '@helsenorge/designsystem-react/components/Icons/ArmFlexing';
export const ArmFlexing = ArmFlexing_;
import ArrowDown_ from '@helsenorge/designsystem-react/components/Icons/ArrowDown';
export const ArrowDown = ArrowDown_;
import ArrowLeft_ from '@helsenorge/designsystem-react/components/Icons/ArrowLeft';
export const ArrowLeft = ArrowLeft_;
import ArrowRight_ from '@helsenorge/designsystem-react/components/Icons/ArrowRight';
export const ArrowRight = ArrowRight_;
import ArrowUp_ from '@helsenorge/designsystem-react/components/Icons/ArrowUp';
export const ArrowUp = ArrowUp_;
import ArrowUpRight_ from '@helsenorge/designsystem-react/components/Icons/ArrowUpRight';
export const ArrowUpRight = ArrowUpRight_;
import Attachment_ from '@helsenorge/designsystem-react/components/Icons/Attachment';
export const Attachment = Attachment_;
import Atv_ from '@helsenorge/designsystem-react/components/Icons/Atv';
export const Atv = Atv_;
import Avatar_ from '@helsenorge/designsystem-react/components/Icons/Avatar';
export const Avatar = Avatar_;
import AwakePersonOnPillow_ from '@helsenorge/designsystem-react/components/Icons/AwakePersonOnPillow';
export const AwakePersonOnPillow = AwakePersonOnPillow_;
import Baby_ from '@helsenorge/designsystem-react/components/Icons/Baby';
export const Baby = Baby_;
import BandAid_ from '@helsenorge/designsystem-react/components/Icons/BandAid';
export const BandAid = BandAid_;
import BeerAndPills_ from '@helsenorge/designsystem-react/components/Icons/BeerAndPills';
export const BeerAndPills = BeerAndPills_;
import Bell_ from '@helsenorge/designsystem-react/components/Icons/Bell';
export const Bell = Bell_;
import Bike_ from '@helsenorge/designsystem-react/components/Icons/Bike';
export const Bike = Bike_;
import BirthControl_ from '@helsenorge/designsystem-react/components/Icons/BirthControl';
export const BirthControl = BirthControl_;
import BirthdayCake_ from '@helsenorge/designsystem-react/components/Icons/BirthdayCake';
export const BirthdayCake = BirthdayCake_;
import Boat_ from '@helsenorge/designsystem-react/components/Icons/Boat';
export const Boat = Boat_;
import Body_ from '@helsenorge/designsystem-react/components/Icons/Body';
export const Body = Body_;
import Brain_ from '@helsenorge/designsystem-react/components/Icons/Brain';
export const Brain = Brain_;
import BreastReconstruction_ from '@helsenorge/designsystem-react/components/Icons/BreastReconstruction';
export const BreastReconstruction = BreastReconstruction_;
import BreastRemoval_ from '@helsenorge/designsystem-react/components/Icons/BreastRemoval';
export const BreastRemoval = BreastRemoval_;
import Breasts_ from '@helsenorge/designsystem-react/components/Icons/Breasts';
export const Breasts = Breasts_;
import BrokenHeart_ from '@helsenorge/designsystem-react/components/Icons/BrokenHeart';
export const BrokenHeart = BrokenHeart_;
import BrokenPuzzle_ from '@helsenorge/designsystem-react/components/Icons/BrokenPuzzle';
export const BrokenPuzzle = BrokenPuzzle_;
import Bus_ from '@helsenorge/designsystem-react/components/Icons/Bus';
export const Bus = Bus_;
import Calendar_ from '@helsenorge/designsystem-react/components/Icons/Calendar';
export const Calendar = Calendar_;
import CalendarChange_ from '@helsenorge/designsystem-react/components/Icons/CalendarChange';
export const CalendarChange = CalendarChange_;
import CalendarCheck_ from '@helsenorge/designsystem-react/components/Icons/CalendarCheck';
export const CalendarCheck = CalendarCheck_;
import CalendarEvent_ from '@helsenorge/designsystem-react/components/Icons/CalendarEvent';
export const CalendarEvent = CalendarEvent_;
import CalendarSave_ from '@helsenorge/designsystem-react/components/Icons/CalendarSave';
export const CalendarSave = CalendarSave_;
import Cancer_ from '@helsenorge/designsystem-react/components/Icons/Cancer';
export const Cancer = Cancer_;
import Car_ from '@helsenorge/designsystem-react/components/Icons/Car';
export const Car = Car_;
import Change_ from '@helsenorge/designsystem-react/components/Icons/Change';
export const Change = Change_;
import Check_ from '@helsenorge/designsystem-react/components/Icons/Check';
export const Check = Check_;
import CheckFill_ from '@helsenorge/designsystem-react/components/Icons/CheckFill';
export const CheckFill = CheckFill_;
import CheckOutline_ from '@helsenorge/designsystem-react/components/Icons/CheckOutline';
export const CheckOutline = CheckOutline_;
import Chest_ from '@helsenorge/designsystem-react/components/Icons/Chest';
export const Chest = Chest_;
import ChevronDown_ from '@helsenorge/designsystem-react/components/Icons/ChevronDown';
export const ChevronDown = ChevronDown_;
import ChevronLeft_ from '@helsenorge/designsystem-react/components/Icons/ChevronLeft';
export const ChevronLeft = ChevronLeft_;
import ChevronRight_ from '@helsenorge/designsystem-react/components/Icons/ChevronRight';
export const ChevronRight = ChevronRight_;
import ChevronUp_ from '@helsenorge/designsystem-react/components/Icons/ChevronUp';
export const ChevronUp = ChevronUp_;
import ChevronsDown_ from '@helsenorge/designsystem-react/components/Icons/ChevronsDown';
export const ChevronsDown = ChevronsDown_;
import ChevronsUp_ from '@helsenorge/designsystem-react/components/Icons/ChevronsUp';
export const ChevronsUp = ChevronsUp_;
import ChildPlaying_ from '@helsenorge/designsystem-react/components/Icons/ChildPlaying';
export const ChildPlaying = ChildPlaying_;
import Cigarette_ from '@helsenorge/designsystem-react/components/Icons/Cigarette';
export const Cigarette = Cigarette_;
import Contacts_ from '@helsenorge/designsystem-react/components/Icons/Contacts';
export const Contacts = Contacts_;
import Copy_ from '@helsenorge/designsystem-react/components/Icons/Copy';
export const Copy = Copy_;
import CoronaCertificate_ from '@helsenorge/designsystem-react/components/Icons/CoronaCertificate';
export const CoronaCertificate = CoronaCertificate_;
import Coronavirus_ from '@helsenorge/designsystem-react/components/Icons/Coronavirus';
export const Coronavirus = Coronavirus_;
import Cough_ from '@helsenorge/designsystem-react/components/Icons/Cough';
export const Cough = Cough_;
import CriticalHealthInfo_ from '@helsenorge/designsystem-react/components/Icons/CriticalHealthInfo';
export const CriticalHealthInfo = CriticalHealthInfo_;
import Cross_ from '@helsenorge/designsystem-react/components/Icons/Cross';
export const Cross = Cross_;
import DataExchange_ from '@helsenorge/designsystem-react/components/Icons/DataExchange';
export const DataExchange = DataExchange_;
import DataReceived_ from '@helsenorge/designsystem-react/components/Icons/DataReceived';
export const DataReceived = DataReceived_;
import DataSent_ from '@helsenorge/designsystem-react/components/Icons/DataSent';
export const DataSent = DataSent_;
import Depression_ from '@helsenorge/designsystem-react/components/Icons/Depression';
export const Depression = Depression_;
import DigestiveSystem_ from '@helsenorge/designsystem-react/components/Icons/DigestiveSystem';
export const DigestiveSystem = DigestiveSystem_;
import Dizzy_ from '@helsenorge/designsystem-react/components/Icons/Dizzy';
export const Dizzy = Dizzy_;
import Documents_ from '@helsenorge/designsystem-react/components/Icons/Documents';
export const Documents = Documents_;
import Dog_ from '@helsenorge/designsystem-react/components/Icons/Dog';
export const Dog = Dog_;
import DonorCard_ from '@helsenorge/designsystem-react/components/Icons/DonorCard';
export const DonorCard = DonorCard_;
import Download_ from '@helsenorge/designsystem-react/components/Icons/Download';
export const Download = Download_;
import Draft_ from '@helsenorge/designsystem-react/components/Icons/Draft';
export const Draft = Draft_;
import EChat_ from '@helsenorge/designsystem-react/components/Icons/EChat';
export const EChat = EChat_;
import EarNoseThroat_ from '@helsenorge/designsystem-react/components/Icons/EarNoseThroat';
export const EarNoseThroat = EarNoseThroat_;
import ElderlyPerson_ from '@helsenorge/designsystem-react/components/Icons/ElderlyPerson';
export const ElderlyPerson = ElderlyPerson_;
import Embolization_ from '@helsenorge/designsystem-react/components/Icons/Embolization';
export const Embolization = Embolization_;
import EmoticonAnnoyed_ from '@helsenorge/designsystem-react/components/Icons/EmoticonAnnoyed';
export const EmoticonAnnoyed = EmoticonAnnoyed_;
import EmoticonDelighted_ from '@helsenorge/designsystem-react/components/Icons/EmoticonDelighted';
export const EmoticonDelighted = EmoticonDelighted_;
import EmoticonDisappointed_ from '@helsenorge/designsystem-react/components/Icons/EmoticonDisappointed';
export const EmoticonDisappointed = EmoticonDisappointed_;
import EmoticonHappy_ from '@helsenorge/designsystem-react/components/Icons/EmoticonHappy';
export const EmoticonHappy = EmoticonHappy_;
import EmoticonMeh_ from '@helsenorge/designsystem-react/components/Icons/EmoticonMeh';
export const EmoticonMeh = EmoticonMeh_;
import EnterFullScreen_ from '@helsenorge/designsystem-react/components/Icons/EnterFullScreen';
export const EnterFullScreen = EnterFullScreen_;
import Envelope_ from '@helsenorge/designsystem-react/components/Icons/Envelope';
export const Envelope = Envelope_;
import Epilepsy_ from '@helsenorge/designsystem-react/components/Icons/Epilepsy';
export const Epilepsy = Epilepsy_;
import Eraser_ from '@helsenorge/designsystem-react/components/Icons/Eraser';
export const Eraser = Eraser_;
import ErrorSignFill_ from '@helsenorge/designsystem-react/components/Icons/ErrorSignFill';
export const ErrorSignFill = ErrorSignFill_;
import ErrorSignStroke_ from '@helsenorge/designsystem-react/components/Icons/ErrorSignStroke';
export const ErrorSignStroke = ErrorSignStroke_;
import EuropeanHealthCard_ from '@helsenorge/designsystem-react/components/Icons/EuropeanHealthCard';
export const EuropeanHealthCard = EuropeanHealthCard_;
import ExitFullScreen_ from '@helsenorge/designsystem-react/components/Icons/ExitFullScreen';
export const ExitFullScreen = ExitFullScreen_;
import Eye_ from '@helsenorge/designsystem-react/components/Icons/Eye';
export const Eye = Eye_;
import Facebook_ from '@helsenorge/designsystem-react/components/Icons/Facebook';
export const Facebook = Facebook_;
import Female_ from '@helsenorge/designsystem-react/components/Icons/Female';
export const Female = Female_;
import FemaleDoctor_ from '@helsenorge/designsystem-react/components/Icons/FemaleDoctor';
export const FemaleDoctor = FemaleDoctor_;
import Ferry_ from '@helsenorge/designsystem-react/components/Icons/Ferry';
export const Ferry = Ferry_;
import Filter_ from '@helsenorge/designsystem-react/components/Icons/Filter';
export const Filter = Filter_;
import FingerBleed_ from '@helsenorge/designsystem-react/components/Icons/FingerBleed';
export const FingerBleed = FingerBleed_;
import FirstAidKit_ from '@helsenorge/designsystem-react/components/Icons/FirstAidKit';
export const FirstAidKit = FirstAidKit_;
import FloppyDisk_ from '@helsenorge/designsystem-react/components/Icons/FloppyDisk';
export const FloppyDisk = FloppyDisk_;
import Football_ from '@helsenorge/designsystem-react/components/Icons/Football';
export const Football = Football_;
import Form_ from '@helsenorge/designsystem-react/components/Icons/Form';
export const Form = Form_;
import Forward_ from '@helsenorge/designsystem-react/components/Icons/Forward';
export const Forward = Forward_;
import Gallery_ from '@helsenorge/designsystem-react/components/Icons/Gallery';
export const Gallery = Gallery_;
import Garden_ from '@helsenorge/designsystem-react/components/Icons/Garden';
export const Garden = Garden_;
import GasCan_ from '@helsenorge/designsystem-react/components/Icons/GasCan';
export const GasCan = GasCan_;
import GenderIdentity_ from '@helsenorge/designsystem-react/components/Icons/GenderIdentity';
export const GenderIdentity = GenderIdentity_;
import Globe_ from '@helsenorge/designsystem-react/components/Icons/Globe';
export const Globe = Globe_;
import Group_ from '@helsenorge/designsystem-react/components/Icons/Group';
export const Group = Group_;
import HandWaving_ from '@helsenorge/designsystem-react/components/Icons/HandWaving';
export const HandWaving = HandWaving_;
import HandWithDisease_ from '@helsenorge/designsystem-react/components/Icons/HandWithDisease';
export const HandWithDisease = HandWithDisease_;
import HealthClinic_ from '@helsenorge/designsystem-react/components/Icons/HealthClinic';
export const HealthClinic = HealthClinic_;
import HealthWarning_ from '@helsenorge/designsystem-react/components/Icons/HealthWarning';
export const HealthWarning = HealthWarning_;
import Heart_ from '@helsenorge/designsystem-react/components/Icons/Heart';
export const Heart = Heart_;
import HelpSign_ from '@helsenorge/designsystem-react/components/Icons/HelpSign';
export const HelpSign = HelpSign_;
import HelpingHand_ from '@helsenorge/designsystem-react/components/Icons/HelpingHand';
export const HelpingHand = HelpingHand_;
import Hemodialysis_ from '@helsenorge/designsystem-react/components/Icons/Hemodialysis';
export const Hemodialysis = Hemodialysis_;
import Hiker_ from '@helsenorge/designsystem-react/components/Icons/Hiker';
export const Hiker = Hiker_;
import Hipprosthesis_ from '@helsenorge/designsystem-react/components/Icons/Hipprosthesis';
export const Hipprosthesis = Hipprosthesis_;
import History_ from '@helsenorge/designsystem-react/components/Icons/History';
export const History = History_;
import HivAndAids_ from '@helsenorge/designsystem-react/components/Icons/HivAndAids';
export const HivAndAids = HivAndAids_;
import Home_ from '@helsenorge/designsystem-react/components/Icons/Home';
export const Home = Home_;
import Hormone_ from '@helsenorge/designsystem-react/components/Icons/Hormone';
export const Hormone = Hormone_;
import Hospital_ from '@helsenorge/designsystem-react/components/Icons/Hospital';
export const Hospital = Hospital_;
import Hourglass_ from '@helsenorge/designsystem-react/components/Icons/Hourglass';
export const Hourglass = Hourglass_;
import ImgFile_ from '@helsenorge/designsystem-react/components/Icons/ImgFile';
export const ImgFile = ImgFile_;
import Inbox_ from '@helsenorge/designsystem-react/components/Icons/Inbox';
export const Inbox = Inbox_;
import InfoSignFill_ from '@helsenorge/designsystem-react/components/Icons/InfoSignFill';
export const InfoSignFill = InfoSignFill_;
import InfoSignStroke_ from '@helsenorge/designsystem-react/components/Icons/InfoSignStroke';
export const InfoSignStroke = InfoSignStroke_;
import Instagram_ from '@helsenorge/designsystem-react/components/Icons/Instagram';
export const Instagram = Instagram_;
import Intravenous_ from '@helsenorge/designsystem-react/components/Icons/Intravenous';
export const Intravenous = Intravenous_;
import JointPain_ from '@helsenorge/designsystem-react/components/Icons/JointPain';
export const JointPain = JointPain_;
import Journal_ from '@helsenorge/designsystem-react/components/Icons/Journal';
export const Journal = Journal_;
import JpgFile_ from '@helsenorge/designsystem-react/components/Icons/JpgFile';
export const JpgFile = JpgFile_;
import Kidney_ from '@helsenorge/designsystem-react/components/Icons/Kidney';
export const Kidney = Kidney_;
import KitchenScale_ from '@helsenorge/designsystem-react/components/Icons/KitchenScale';
export const KitchenScale = KitchenScale_;
import Kjernejournal_ from '@helsenorge/designsystem-react/components/Icons/Kjernejournal';
export const Kjernejournal = Kjernejournal_;
import Laboratory_ from '@helsenorge/designsystem-react/components/Icons/Laboratory';
export const Laboratory = Laboratory_;
import LaptopBlog_ from '@helsenorge/designsystem-react/components/Icons/LaptopBlog';
export const LaptopBlog = LaptopBlog_;
import LawBook_ from '@helsenorge/designsystem-react/components/Icons/LawBook';
export const LawBook = LawBook_;
import LightBulb_ from '@helsenorge/designsystem-react/components/Icons/LightBulb';
export const LightBulb = LightBulb_;
import List_ from '@helsenorge/designsystem-react/components/Icons/List';
export const List = List_;
import Location_ from '@helsenorge/designsystem-react/components/Icons/Location';
export const Location = Location_;
import Lock_ from '@helsenorge/designsystem-react/components/Icons/Lock';
export const Lock = Lock_;
import Lungs_ from '@helsenorge/designsystem-react/components/Icons/Lungs';
export const Lungs = Lungs_;
import Makeup_ from '@helsenorge/designsystem-react/components/Icons/Makeup';
export const Makeup = Makeup_;
import MaleDoctor_ from '@helsenorge/designsystem-react/components/Icons/MaleDoctor';
export const MaleDoctor = MaleDoctor_;
import MaleDoctorAndPerson_ from '@helsenorge/designsystem-react/components/Icons/MaleDoctorAndPerson';
export const MaleDoctorAndPerson = MaleDoctorAndPerson_;
import MaleGenitalia_ from '@helsenorge/designsystem-react/components/Icons/MaleGenitalia';
export const MaleGenitalia = MaleGenitalia_;
import Medicine_ from '@helsenorge/designsystem-react/components/Icons/Medicine';
export const Medicine = Medicine_;
import MedicineWarning_ from '@helsenorge/designsystem-react/components/Icons/MedicineWarning';
export const MedicineWarning = MedicineWarning_;
import MentalHealthAdult_ from '@helsenorge/designsystem-react/components/Icons/MentalHealthAdult';
export const MentalHealthAdult = MentalHealthAdult_;
import MentalHealthChild_ from '@helsenorge/designsystem-react/components/Icons/MentalHealthChild';
export const MentalHealthChild = MentalHealthChild_;
import Menu_ from '@helsenorge/designsystem-react/components/Icons/Menu';
export const Menu = Menu_;
import Microscope_ from '@helsenorge/designsystem-react/components/Icons/Microscope';
export const Microscope = Microscope_;
import Minus_ from '@helsenorge/designsystem-react/components/Icons/Minus';
export const Minus = Minus_;
import Mirror_ from '@helsenorge/designsystem-react/components/Icons/Mirror';
export const Mirror = Mirror_;
import MobilePhone_ from '@helsenorge/designsystem-react/components/Icons/MobilePhone';
export const MobilePhone = MobilePhone_;
import MotherHoldingBaby_ from '@helsenorge/designsystem-react/components/Icons/MotherHoldingBaby';
export const MotherHoldingBaby = MotherHoldingBaby_;
import MuscleBack_ from '@helsenorge/designsystem-react/components/Icons/MuscleBack';
export const MuscleBack = MuscleBack_;
import MuscleLeg_ from '@helsenorge/designsystem-react/components/Icons/MuscleLeg';
export const MuscleLeg = MuscleLeg_;
import Mushroom_ from '@helsenorge/designsystem-react/components/Icons/Mushroom';
export const Mushroom = Mushroom_;
import Music_ from '@helsenorge/designsystem-react/components/Icons/Music';
export const Music = Music_;
import MusselsAndSalt_ from '@helsenorge/designsystem-react/components/Icons/MusselsAndSalt';
export const MusselsAndSalt = MusselsAndSalt_;
import NoAccess_ from '@helsenorge/designsystem-react/components/Icons/NoAccess';
export const NoAccess = NoAccess_;
import NoEye_ from '@helsenorge/designsystem-react/components/Icons/NoEye';
export const NoEye = NoEye_;
import NoFilter_ from '@helsenorge/designsystem-react/components/Icons/NoFilter';
export const NoFilter = NoFilter_;
import Notepad_ from '@helsenorge/designsystem-react/components/Icons/Notepad';
export const Notepad = Notepad_;
import Osteotomy_ from '@helsenorge/designsystem-react/components/Icons/Osteotomy';
export const Osteotomy = Osteotomy_;
import PaintRoller_ from '@helsenorge/designsystem-react/components/Icons/PaintRoller';
export const PaintRoller = PaintRoller_;
import PaperPlane_ from '@helsenorge/designsystem-react/components/Icons/PaperPlane';
export const PaperPlane = PaperPlane_;
import PatientAndPerson_ from '@helsenorge/designsystem-react/components/Icons/PatientAndPerson';
export const PatientAndPerson = PatientAndPerson_;
import Pause_ from '@helsenorge/designsystem-react/components/Icons/Pause';
export const Pause = Pause_;
import PdfFile_ from '@helsenorge/designsystem-react/components/Icons/PdfFile';
export const PdfFile = PdfFile_;
import Pencil_ from '@helsenorge/designsystem-react/components/Icons/Pencil';
export const Pencil = Pencil_;
import PeopleTalking_ from '@helsenorge/designsystem-react/components/Icons/PeopleTalking';
export const PeopleTalking = PeopleTalking_;
import Peritonealdialysis_ from '@helsenorge/designsystem-react/components/Icons/Peritonealdialysis';
export const Peritonealdialysis = Peritonealdialysis_;
import Person_ from '@helsenorge/designsystem-react/components/Icons/Person';
export const Person = Person_;
import PersonAndPatient_ from '@helsenorge/designsystem-react/components/Icons/PersonAndPatient';
export const PersonAndPatient = PersonAndPatient_;
import PersonInXRayMachine_ from '@helsenorge/designsystem-react/components/Icons/PersonInXRayMachine';
export const PersonInXRayMachine = PersonInXRayMachine_;
import PersonOverweight_ from '@helsenorge/designsystem-react/components/Icons/PersonOverweight';
export const PersonOverweight = PersonOverweight_;
import PersonRelaxing_ from '@helsenorge/designsystem-react/components/Icons/PersonRelaxing';
export const PersonRelaxing = PersonRelaxing_;
import PersonWithBrain_ from '@helsenorge/designsystem-react/components/Icons/PersonWithBrain';
export const PersonWithBrain = PersonWithBrain_;
import PersonWithBrokenArm_ from '@helsenorge/designsystem-react/components/Icons/PersonWithBrokenArm';
export const PersonWithBrokenArm = PersonWithBrokenArm_;
import PersonWithCrutches_ from '@helsenorge/designsystem-react/components/Icons/PersonWithCrutches';
export const PersonWithCrutches = PersonWithCrutches_;
import PersonWithJaw_ from '@helsenorge/designsystem-react/components/Icons/PersonWithJaw';
export const PersonWithJaw = PersonWithJaw_;
import PersonWithMagnifyingGlass_ from '@helsenorge/designsystem-react/components/Icons/PersonWithMagnifyingGlass';
export const PersonWithMagnifyingGlass = PersonWithMagnifyingGlass_;
import PersonWithSenses_ from '@helsenorge/designsystem-react/components/Icons/PersonWithSenses';
export const PersonWithSenses = PersonWithSenses_;
import PersonWorking_ from '@helsenorge/designsystem-react/components/Icons/PersonWorking';
export const PersonWorking = PersonWorking_;
import PersonalPlan_ from '@helsenorge/designsystem-react/components/Icons/PersonalPlan';
export const PersonalPlan = PersonalPlan_;
import PizzaSlice_ from '@helsenorge/designsystem-react/components/Icons/PizzaSlice';
export const PizzaSlice = PizzaSlice_;
import Plane_ from '@helsenorge/designsystem-react/components/Icons/Plane';
export const Plane = Plane_;
import Plant_ from '@helsenorge/designsystem-react/components/Icons/Plant';
export const Plant = Plant_;
import Play_ from '@helsenorge/designsystem-react/components/Icons/Play';
export const Play = Play_;
import PlusLarge_ from '@helsenorge/designsystem-react/components/Icons/PlusLarge';
export const PlusLarge = PlusLarge_;
import PlusSmall_ from '@helsenorge/designsystem-react/components/Icons/PlusSmall';
export const PlusSmall = PlusSmall_;
import PngFile_ from '@helsenorge/designsystem-react/components/Icons/PngFile';
export const PngFile = PngFile_;
import Podcast_ from '@helsenorge/designsystem-react/components/Icons/Podcast';
export const Podcast = Podcast_;
import PoisonInformation_ from '@helsenorge/designsystem-react/components/Icons/PoisonInformation';
export const PoisonInformation = PoisonInformation_;
import Pregnant_ from '@helsenorge/designsystem-react/components/Icons/Pregnant';
export const Pregnant = Pregnant_;
import Printer_ from '@helsenorge/designsystem-react/components/Icons/Printer';
export const Printer = Printer_;
import Psychosis_ from '@helsenorge/designsystem-react/components/Icons/Psychosis';
export const Psychosis = Psychosis_;
import Publication_ from '@helsenorge/designsystem-react/components/Icons/Publication';
export const Publication = Publication_;
import Puzzle_ from '@helsenorge/designsystem-react/components/Icons/Puzzle';
export const Puzzle = Puzzle_;
import QrCode_ from '@helsenorge/designsystem-react/components/Icons/QrCode';
export const QrCode = QrCode_;
import Quarrel_ from '@helsenorge/designsystem-react/components/Icons/Quarrel';
export const Quarrel = Quarrel_;
import RadioTherapy_ from '@helsenorge/designsystem-react/components/Icons/RadioTherapy';
export const RadioTherapy = RadioTherapy_;
import RadioactiveTreatment_ from '@helsenorge/designsystem-react/components/Icons/RadioactiveTreatment';
export const RadioactiveTreatment = RadioactiveTreatment_;
import Radioiodine_ from '@helsenorge/designsystem-react/components/Icons/Radioiodine';
export const Radioiodine = Radioiodine_;
import Receipt_ from '@helsenorge/designsystem-react/components/Icons/Receipt';
export const Receipt = Receipt_;
import Receptionist_ from '@helsenorge/designsystem-react/components/Icons/Receptionist';
export const Receptionist = Receptionist_;
import Recovery_ from '@helsenorge/designsystem-react/components/Icons/Recovery';
export const Recovery = Recovery_;
import Referral_ from '@helsenorge/designsystem-react/components/Icons/Referral';
export const Referral = Referral_;
import Refresh_ from '@helsenorge/designsystem-react/components/Icons/Refresh';
export const Refresh = Refresh_;
import Refund_ from '@helsenorge/designsystem-react/components/Icons/Refund';
export const Refund = Refund_;
import Reply_ from '@helsenorge/designsystem-react/components/Icons/Reply';
export const Reply = Reply_;
import Rocket_ from '@helsenorge/designsystem-react/components/Icons/Rocket';
export const Rocket = Rocket_;
import RtfFile_ from '@helsenorge/designsystem-react/components/Icons/RtfFile';
export const RtfFile = RtfFile_;
import STDs_ from '@helsenorge/designsystem-react/components/Icons/STDs';
export const STDs = STDs_;
import Save_ from '@helsenorge/designsystem-react/components/Icons/Save';
export const Save = Save_;
import Scale_ from '@helsenorge/designsystem-react/components/Icons/Scale';
export const Scale = Scale_;
import Search_ from '@helsenorge/designsystem-react/components/Icons/Search';
export const Search = Search_;
import SectionSign_ from '@helsenorge/designsystem-react/components/Icons/SectionSign';
export const SectionSign = SectionSign_;
import Settings_ from '@helsenorge/designsystem-react/components/Icons/Settings';
export const Settings = Settings_;
import Sexualorientation_ from '@helsenorge/designsystem-react/components/Icons/Sexualorientation';
export const Sexualorientation = Sexualorientation_;
import ShakingHand_ from '@helsenorge/designsystem-react/components/Icons/ShakingHand';
export const ShakingHand = ShakingHand_;
import Share_ from '@helsenorge/designsystem-react/components/Icons/Share';
export const Share = Share_;
import Shield_ from '@helsenorge/designsystem-react/components/Icons/Shield';
export const Shield = Shield_;
import ShuntOperation_ from '@helsenorge/designsystem-react/components/Icons/ShuntOperation';
export const ShuntOperation = ShuntOperation_;
import Skeleton_ from '@helsenorge/designsystem-react/components/Icons/Skeleton';
export const Skeleton = Skeleton_;
import Skin_ from '@helsenorge/designsystem-react/components/Icons/Skin';
export const Skin = Skin_;
import Snake_ from '@helsenorge/designsystem-react/components/Icons/Snake';
export const Snake = Snake_;
import Snapchat_ from '@helsenorge/designsystem-react/components/Icons/Snapchat';
export const Snapchat = Snapchat_;
import SortDown_ from '@helsenorge/designsystem-react/components/Icons/SortDown';
export const SortDown = SortDown_;
import SortUp_ from '@helsenorge/designsystem-react/components/Icons/SortUp';
export const SortUp = SortUp_;
import SpeechBubble_ from '@helsenorge/designsystem-react/components/Icons/SpeechBubble';
export const SpeechBubble = SpeechBubble_;
import Spray_ from '@helsenorge/designsystem-react/components/Icons/Spray';
export const Spray = Spray_;
import Stopwatch_ from '@helsenorge/designsystem-react/components/Icons/Stopwatch';
export const Stopwatch = Stopwatch_;
import SupportingPerson_ from '@helsenorge/designsystem-react/components/Icons/SupportingPerson';
export const SupportingPerson = SupportingPerson_;
import Surgery_ from '@helsenorge/designsystem-react/components/Icons/Surgery';
export const Surgery = Surgery_;
import Syringe_ from '@helsenorge/designsystem-react/components/Icons/Syringe';
export const Syringe = Syringe_;
import Taxi_ from '@helsenorge/designsystem-react/components/Icons/Taxi';
export const Taxi = Taxi_;
import TeddyBear_ from '@helsenorge/designsystem-react/components/Icons/TeddyBear';
export const TeddyBear = TeddyBear_;
import Teenagers_ from '@helsenorge/designsystem-react/components/Icons/Teenagers';
export const Teenagers = Teenagers_;
import ThinkingAboutBaby_ from '@helsenorge/designsystem-react/components/Icons/ThinkingAboutBaby';
export const ThinkingAboutBaby = ThinkingAboutBaby_;
import Ticket_ from '@helsenorge/designsystem-react/components/Icons/Ticket';
export const Ticket = Ticket_;
import TimePassing_ from '@helsenorge/designsystem-react/components/Icons/TimePassing';
export const TimePassing = TimePassing_;
import Toolbox_ from '@helsenorge/designsystem-react/components/Icons/Toolbox';
export const Toolbox = Toolbox_;
import Tooth_ from '@helsenorge/designsystem-react/components/Icons/Tooth';
export const Tooth = Tooth_;
import TotalKneeProsthesis_ from '@helsenorge/designsystem-react/components/Icons/TotalKneeProsthesis';
export const TotalKneeProsthesis = TotalKneeProsthesis_;
import Train_ from '@helsenorge/designsystem-react/components/Icons/Train';
export const Train = Train_;
import Transplantation_ from '@helsenorge/designsystem-react/components/Icons/Transplantation';
export const Transplantation = Transplantation_;
import TrashCan_ from '@helsenorge/designsystem-react/components/Icons/TrashCan';
export const TrashCan = TrashCan_;
import Twitter_ from '@helsenorge/designsystem-react/components/Icons/Twitter';
export const Twitter = Twitter_;
import Undo_ from '@helsenorge/designsystem-react/components/Icons/Undo';
export const Undo = Undo_;
import UniProsthesis_ from '@helsenorge/designsystem-react/components/Icons/UniProsthesis';
export const UniProsthesis = UniProsthesis_;
import Upload_ from '@helsenorge/designsystem-react/components/Icons/Upload';
export const Upload = Upload_;
import UserOrganization_ from '@helsenorge/designsystem-react/components/Icons/UserOrganization';
export const UserOrganization = UserOrganization_;
import Vaccine_ from '@helsenorge/designsystem-react/components/Icons/Vaccine';
export const Vaccine = Vaccine_;
import VerticalDots_ from '@helsenorge/designsystem-react/components/Icons/VerticalDots';
export const VerticalDots = VerticalDots_;
import VideoCamera_ from '@helsenorge/designsystem-react/components/Icons/VideoCamera';
export const VideoCamera = VideoCamera_;
import VideoChat_ from '@helsenorge/designsystem-react/components/Icons/VideoChat';
export const VideoChat = VideoChat_;
import Wallet_ from '@helsenorge/designsystem-react/components/Icons/Wallet';
export const Wallet = Wallet_;
import Watch_ from '@helsenorge/designsystem-react/components/Icons/Watch';
export const Watch = Watch_;
import Website_ from '@helsenorge/designsystem-react/components/Icons/Website';
export const Website = Website_;
import Wheelchair_ from '@helsenorge/designsystem-react/components/Icons/Wheelchair';
export const Wheelchair = Wheelchair_;
import WheelchairActive_ from '@helsenorge/designsystem-react/components/Icons/WheelchairActive';
export const WheelchairActive = WheelchairActive_;
import Window_ from '@helsenorge/designsystem-react/components/Icons/Window';
export const Window = Window_;
import WordDocument_ from '@helsenorge/designsystem-react/components/Icons/WordDocument';
export const WordDocument = WordDocument_;
import WorkSuitcase_ from '@helsenorge/designsystem-react/components/Icons/WorkSuitcase';
export const WorkSuitcase = WorkSuitcase_;
import X_ from '@helsenorge/designsystem-react/components/Icons/X';
export const X = X_;
import XOutline_ from '@helsenorge/designsystem-react/components/Icons/XOutline';
export const XOutline = XOutline_;
import XmlFile_ from '@helsenorge/designsystem-react/components/Icons/XmlFile';
export const XmlFile = XmlFile_;
import YouTube_ from '@helsenorge/designsystem-react/components/Icons/YouTube';
export const YouTube = YouTube_;
import Zoom_ from '@helsenorge/designsystem-react/components/Icons/Zoom';
export const Zoom = Zoom_;


export const allSvgIcons = [ { module: ActiveMonitoring, name: "ActiveMonitoring", alternativeName: "Aktiv overvåkning", categories: "Samvalg", }, { module: AcupunctureBack, name: "AcupunctureBack", alternativeName: "Akupunktur rygg", categories: "Samvalg, Generisk", }, { module: AlarmClock, name: "AlarmClock", alternativeName: "Vekkeklokke", categories: "Generisk", }, { module: AlertSignFill, name: "AlertSignFill", alternativeName: "", categories: "", }, { module: AlertSignStroke, name: "AlertSignStroke", alternativeName: "", categories: "", }, { module: Amputation, name: "Amputation", alternativeName: "Amputasjon", categories: "Behandling, Personer", }, { module: Anxiety, name: "Anxiety", alternativeName: "Angst", categories: "Psykisk helse, Sykdom", }, { module: Apple, name: "Apple", alternativeName: "Eple", categories: "Livsstil", }, { module: Archive, name: "Archive", alternativeName: "Arkivboks", categories: "Tjeneste", }, { module: ArmFlexing, name: "ArmFlexing", alternativeName: "Viser muskler (arm)", categories: "Livsstil, Anatomi", }, { module: ArrowDown, name: "ArrowDown", alternativeName: "", categories: "", }, { module: ArrowLeft, name: "ArrowLeft", alternativeName: "Ventrepil", categories: "System", }, { module: ArrowRight, name: "ArrowRight", alternativeName: "Høyrepil", categories: "System", }, { module: ArrowUp, name: "ArrowUp", alternativeName: "", categories: "", }, { module: ArrowUpRight, name: "ArrowUpRight", alternativeName: "Pil oppover mot høyre", categories: "System", }, { module: Attachment, name: "Attachment", alternativeName: "Vedlegg", categories: "Generisk", }, { module: Atv, name: "Atv", alternativeName: "ATV", categories: "Kjøretøy", }, { module: Avatar, name: "Avatar", alternativeName: "", categories: "", }, { module: AwakePersonOnPillow, name: "AwakePersonOnPillow", alternativeName: "Person som ikke får sove", categories: "Generisk, Sykdom", }, { module: Baby, name: "Baby", alternativeName: "Baby", categories: "Gravid og fødsel", }, { module: BandAid, name: "BandAid", alternativeName: "Plaster", categories: "Generisk, Behandling, Samvalg", }, { module: BeerAndPills, name: "BeerAndPills", alternativeName: "Rusmidler", categories: "Giftinformasjonen, Livsstil", }, { module: Bell, name: "Bell", alternativeName: "Varsel", categories: "Generisk", }, { module: Bike, name: "Bike", alternativeName: "Sykkel", categories: "Kjøretøy, Livsstil", }, { module: BirthControl, name: "BirthControl", alternativeName: "Prevensjon", categories: "Generisk", }, { module: BirthdayCake, name: "BirthdayCake", alternativeName: "Bursdagskake", categories: "Gravid og fødsel, Generisk", }, { module: Boat, name: "Boat", alternativeName: "Båt", categories: "Kjøretøy", }, { module: Body, name: "Body", alternativeName: "Kropp", categories: "Anatomi, Personer", }, { module: Brain, name: "Brain", alternativeName: "Hjerne", categories: "Sykdom, Anatomi", }, { module: BreastReconstruction, name: "BreastReconstruction", alternativeName: "Brystrekonstruksjon", categories: "Samvalg", }, { module: BreastRemoval, name: "BreastRemoval", alternativeName: "Brystfjerning", categories: "Samvalg", }, { module: Breasts, name: "Breasts", alternativeName: "Pupper", categories: "Anatomi, Sykdom, Samvalg", }, { module: BrokenHeart, name: "BrokenHeart", alternativeName: "Knust hjerte", categories: "Generisk", }, { module: BrokenPuzzle, name: "BrokenPuzzle", alternativeName: "Ødelagt pusslespill", categories: "Generisk", }, { module: Bus, name: "Bus", alternativeName: "Buss", categories: "Tjeneste, Kjøretøy", }, { module: Calendar, name: "Calendar", alternativeName: "Kalender", categories: "Tjeneste, Generisk", }, { module: CalendarChange, name: "CalendarChange", alternativeName: "Kalender endring", categories: "System, Generisk", }, { module: CalendarCheck, name: "CalendarCheck", alternativeName: "Kalender ok", categories: "System, Generisk", }, { module: CalendarEvent, name: "CalendarEvent", alternativeName: "Kalenderhendelse", categories: "Generisk", }, { module: CalendarSave, name: "CalendarSave", alternativeName: "Lagre i kalender", categories: "System", }, { module: Cancer, name: "Cancer", alternativeName: "Kreft", categories: "Sykdom", }, { module: Car, name: "Car", alternativeName: "Bil", categories: "Kjøretøy", }, { module: Change, name: "Change", alternativeName: "Endre", categories: "System, Generisk", }, { module: Check, name: "Check", alternativeName: "Avsjekket", categories: "Generisk", }, { module: CheckFill, name: "CheckFill", alternativeName: "Utfylt sjekkboks", categories: "System", }, { module: CheckOutline, name: "CheckOutline", alternativeName: "Avhukning", categories: "System, Generisk", }, { module: Chest, name: "Chest", alternativeName: "Kiste", categories: "Generisk", }, { module: ChevronDown, name: "ChevronDown", alternativeName: "Nedover halvpil", categories: "System", }, { module: ChevronLeft, name: "ChevronLeft", alternativeName: "Venstre halvpil", categories: "System", }, { module: ChevronRight, name: "ChevronRight", alternativeName: "Høyre halvpil", categories: "System", }, { module: ChevronUp, name: "ChevronUp", alternativeName: "Oppover halvpil", categories: "System", }, { module: ChevronsDown, name: "ChevronsDown", alternativeName: "Dobbelpil ned", categories: "System, Generisk", }, { module: ChevronsUp, name: "ChevronsUp", alternativeName: "Dobbeltpil opp", categories: "System, Generisk", }, { module: ChildPlaying, name: "ChildPlaying", alternativeName: "Barn leker", categories: "Livsstil, Personer", }, { module: Cigarette, name: "Cigarette", alternativeName: "Sigarett", categories: "Livsstil", }, { module: Contacts, name: "Contacts", alternativeName: "Helsekontakter", categories: "Tjeneste", }, { module: Copy, name: "Copy", alternativeName: "Kopi", categories: "System", }, { module: CoronaCertificate, name: "CoronaCertificate", alternativeName: "Koronasertifikat", categories: "Tjeneste", }, { module: Coronavirus, name: "Coronavirus", alternativeName: "Koronavirus", categories: "Sykdom", }, { module: Cough, name: "Cough", alternativeName: "Hoste", categories: "Sykdom, Behandling", }, { module: CriticalHealthInfo, name: "CriticalHealthInfo", alternativeName: "Sykdom og kritisk informasjon", categories: "Tjeneste", }, { module: Cross, name: "Cross", alternativeName: "Kryss", categories: "System", }, { module: DataExchange, name: "DataExchange", alternativeName: "Datautveklsling", categories: "System, Generisk", }, { module: DataReceived, name: "DataReceived", alternativeName: "Data motatt", categories: "System, Generisk", }, { module: DataSent, name: "DataSent", alternativeName: "Data sendt", categories: "System, Generisk", }, { module: Depression, name: "Depression", alternativeName: "Depresjon", categories: "Psykisk helse, Sykdom", }, { module: DigestiveSystem, name: "DigestiveSystem", alternativeName: "Fordøyelsessystem", categories: "Sykdom, Anatomi", }, { module: Dizzy, name: "Dizzy", alternativeName: "Svimmel", categories: "Sykdom", }, { module: Documents, name: "Documents", alternativeName: "Dokumenter", categories: "Tjeneste, Generisk", }, { module: Dog, name: "Dog", alternativeName: "Hund", categories: "Giftinformasjonen, Dyr", }, { module: DonorCard, name: "DonorCard", alternativeName: "Donorkort", categories: "Tjeneste", }, { module: Download, name: "Download", alternativeName: "Last ned", categories: "System, Generisk", }, { module: Draft, name: "Draft", alternativeName: "Kladd", categories: "Generisk", }, { module: EChat, name: "EChat", alternativeName: "Sosiale medier (generisk)", categories: "Sosiale medier, Generisk", }, { module: EarNoseThroat, name: "EarNoseThroat", alternativeName: "Øre - nese - hals", categories: "Sykdom, Anatomi", }, { module: ElderlyPerson, name: "ElderlyPerson", alternativeName: "Eldre", categories: "Livsstil, Personer", }, { module: Embolization, name: "Embolization", alternativeName: "Cyster", categories: "Samvalg, Sykdom", }, { module: EmoticonAnnoyed, name: "EmoticonAnnoyed", alternativeName: "Emoji Irritert", categories: "Generisk", }, { module: EmoticonDelighted, name: "EmoticonDelighted", alternativeName: "Emoji Lykkelig", categories: "Generisk", }, { module: EmoticonDisappointed, name: "EmoticonDisappointed", alternativeName: "Emoji Skuffet", categories: "Generisk", }, { module: EmoticonHappy, name: "EmoticonHappy", alternativeName: "Emoji Glad", categories: "Generisk", }, { module: EmoticonMeh, name: "EmoticonMeh", alternativeName: "Emoji Nøytral", categories: "Generisk", }, { module: EnterFullScreen, name: "EnterFullScreen", alternativeName: "Fullskjermvisning", categories: "System", }, { module: Envelope, name: "Envelope", alternativeName: "Konvolutt", categories: "Tjeneste, Generisk", }, { module: Epilepsy, name: "Epilepsy", alternativeName: "Epilepsi", categories: "Sykdom", }, { module: Eraser, name: "Eraser", alternativeName: "Viskelær", categories: "System", }, { module: ErrorSignFill, name: "ErrorSignFill", alternativeName: "Feilmelding (mørk)", categories: "Generisk", }, { module: ErrorSignStroke, name: "ErrorSignStroke", alternativeName: "Feilmelding (lys)", categories: "Generisk", }, { module: EuropeanHealthCard, name: "EuropeanHealthCard", alternativeName: "Europeisk helsetrygdkort", categories: "Tjeneste", }, { module: ExitFullScreen, name: "ExitFullScreen", alternativeName: "Gå ut av fullskjermvisning", categories: "System", }, { module: Eye, name: "Eye", alternativeName: "Øye", categories: "Sykdom, Anatomi", }, { module: Facebook, name: "Facebook", alternativeName: "Facebook", categories: "Sosiale medier", }, { module: Female, name: "Female", alternativeName: "Kvinne- tegn", categories: "Generisk", }, { module: FemaleDoctor, name: "FemaleDoctor", alternativeName: "Kvinnelig lege", categories: "Tjeneste, Personer", }, { module: Ferry, name: "Ferry", alternativeName: "Ferje", categories: "Kjøretøy", }, { module: Filter, name: "Filter", alternativeName: "Filter", categories: "System", }, { module: FingerBleed, name: "FingerBleed", alternativeName: "Finger som blør", categories: "Sykdom, Behandling", }, { module: FirstAidKit, name: "FirstAidKit", alternativeName: "Førstehjelpsskrin", categories: "Giftinformasjonen, Behandling", }, { module: FloppyDisk, name: "FloppyDisk", alternativeName: "Diskett", categories: "Generisk", }, { module: Football, name: "Football", alternativeName: "Fotball", categories: "Giftinformasjonen, Livsstil", }, { module: Form, name: "Form", alternativeName: "Skjema", categories: "Tjeneste, Generisk", }, { module: Forward, name: "Forward", alternativeName: "Pil fremover", categories: "System", }, { module: Gallery, name: "Gallery", alternativeName: "Galleri", categories: "System", }, { module: Garden, name: "Garden", alternativeName: "Hage", categories: "Giftinformasjonen", }, { module: GasCan, name: "GasCan", alternativeName: "Gassbeholder", categories: "Giftinformasjonen", }, { module: GenderIdentity, name: "GenderIdentity", alternativeName: "Kjønnsidentitet", categories: "Generisk, Personer", }, { module: Globe, name: "Globe", alternativeName: "Globus", categories: "Generisk", }, { module: Group, name: "Group", alternativeName: "Gruppe", categories: "Personer", }, { module: HandWaving, name: "HandWaving", alternativeName: "Vinke", categories: "Generisk", }, { module: HandWithDisease, name: "HandWithDisease", alternativeName: "Hånd med utslett", categories: "Sykdom, Anatomi", }, { module: HealthClinic, name: "HealthClinic", alternativeName: "Helsesenter", categories: "Generisk, Behandling", }, { module: HealthWarning, name: "HealthWarning", alternativeName: "Helseadvarsel", categories: "Tjeneste", }, { module: Heart, name: "Heart", alternativeName: "Hjerte", categories: "Sykdom, Anatomi", }, { module: HelpSign, name: "HelpSign", alternativeName: "Spørsmål", categories: "Generisk", }, { module: HelpingHand, name: "HelpingHand", alternativeName: "Hjelpende hånd", categories: "Samvalg", }, { module: Hemodialysis, name: "Hemodialysis", alternativeName: "Hemodialyse", categories: "Samvalg", }, { module: Hiker, name: "Hiker", alternativeName: "Turgåer", categories: "Livsstil, Samvalg", }, { module: Hipprosthesis, name: "Hipprosthesis", alternativeName: "Hofteprotese", categories: "Samvalg", }, { module: History, name: "History", alternativeName: "Historikk", categories: "Generisk", }, { module: HivAndAids, name: "HivAndAids", alternativeName: "HIV og Aids", categories: "Sykdom", }, { module: Home, name: "Home", alternativeName: "Hjem", categories: "Generisk", }, { module: Hormone, name: "Hormone", alternativeName: "Hormoner", categories: "Sykdom, Anatomi", }, { module: Hospital, name: "Hospital", alternativeName: "Sykehus", categories: "Tjeneste, Behandling", }, { module: Hourglass, name: "Hourglass", alternativeName: "Timeglass", categories: "Generisk", }, { module: ImgFile, name: "ImgFile", alternativeName: "Bildefil", categories: "Filtyper", }, { module: Inbox, name: "Inbox", alternativeName: "Innboks", categories: "Generisk", }, { module: InfoSignFill, name: "InfoSignFill", alternativeName: "Informasjon (mørk)", categories: "Generisk", }, { module: InfoSignStroke, name: "InfoSignStroke", alternativeName: "Informasjon (lys)", categories: "Generisk", }, { module: Instagram, name: "Instagram", alternativeName: "Instagram", categories: "Sosiale medier, Generisk", }, { module: Intravenous, name: "Intravenous", alternativeName: "Intravenøs", categories: "Samvalg, Behandling", }, { module: JointPain, name: "JointPain", alternativeName: "Leddsmerte", categories: "Sykdom, Anatomi", }, { module: Journal, name: "Journal", alternativeName: "Pasientjournal", categories: "Tjeneste", }, { module: JpgFile, name: "JpgFile", alternativeName: "Jpg-fil", categories: "Filtyper", }, { module: Kidney, name: "Kidney", alternativeName: "Nyre", categories: "Sykdom, Anatomi", }, { module: KitchenScale, name: "KitchenScale", alternativeName: "Kjøkkenvekt", categories: "Samvalg", }, { module: Kjernejournal, name: "Kjernejournal", alternativeName: "Kjernejournal", categories: "Tjeneste", }, { module: Laboratory, name: "Laboratory", alternativeName: "Laboratorieprøver", categories: "Tjeneste, Behandling", }, { module: LaptopBlog, name: "LaptopBlog", alternativeName: "Laptop blogg", categories: "Generisk, Sosiale medier", }, { module: LawBook, name: "LawBook", alternativeName: "Lovbok", categories: "Generisk", }, { module: LightBulb, name: "LightBulb", alternativeName: "Lyspære", categories: "Generisk", }, { module: List, name: "List", alternativeName: "Liste", categories: "System", }, { module: Location, name: "Location", alternativeName: "Lokasjon", categories: "Generisk", }, { module: Lock, name: "Lock", alternativeName: "Hengelås", categories: "Tjeneste, Generisk", }, { module: Lungs, name: "Lungs", alternativeName: "Lunger", categories: "Sykdom, Anatomi", }, { module: Makeup, name: "Makeup", alternativeName: "Sminke", categories: "Giftinformasjonen", }, { module: MaleDoctor, name: "MaleDoctor", alternativeName: "Mannlig lege", categories: "Tjeneste, Behandling", }, { module: MaleDoctorAndPerson, name: "MaleDoctorAndPerson", alternativeName: "Mannlig lege og pasient", categories: "Behandling, Personer", }, { module: MaleGenitalia, name: "MaleGenitalia", alternativeName: "Mannlig kjønnsorgan", categories: "Sykdom, Anatomi", }, { module: Medicine, name: "Medicine", alternativeName: "Legemidler", categories: "Tjeneste, Behandling, Samvalg", }, { module: MedicineWarning, name: "MedicineWarning", alternativeName: "Meld bivirkninger", categories: "Tjeneste", }, { module: MentalHealthAdult, name: "MentalHealthAdult", alternativeName: "Psykisk helse voksne", categories: "Psykisk helse", }, { module: MentalHealthChild, name: "MentalHealthChild", alternativeName: "Mental helse barn", categories: "Psykisk helse, Sykdom", }, { module: Menu, name: "Menu", alternativeName: "Meny", categories: "System", }, { module: Microscope, name: "Microscope", alternativeName: "Mikroskop", categories: "Tjeneste, Behandling", }, { module: Minus, name: "Minus", alternativeName: "Minus", categories: "System", }, { module: Mirror, name: "Mirror", alternativeName: "Speil", categories: "Generisk", }, { module: MobilePhone, name: "MobilePhone", alternativeName: "Mobiltelefon", categories: "Generisk", }, { module: MotherHoldingBaby, name: "MotherHoldingBaby", alternativeName: "Kvinne holder baby", categories: "Gravid og fødsel", }, { module: MuscleBack, name: "MuscleBack", alternativeName: "Ryggmuskler", categories: "Anatomi", }, { module: MuscleLeg, name: "MuscleLeg", alternativeName: "Leggmuskler", categories: "Anatomi", }, { module: Mushroom, name: "Mushroom", alternativeName: "Sopp", categories: "Giftinformasjonen, Livsstil", }, { module: Music, name: "Music", alternativeName: "Musikk", categories: "Samvalg", }, { module: MusselsAndSalt, name: "MusselsAndSalt", alternativeName: "Blåskjell og saltbøsse", categories: "Giftinformasjonen, Livsstil", }, { module: NoAccess, name: "NoAccess", alternativeName: "", categories: "", }, { module: NoEye, name: "NoEye", alternativeName: "Øye m strek", categories: "System", }, { module: NoFilter, name: "NoFilter", alternativeName: "Fjern filter", categories: "System", }, { module: Notepad, name: "Notepad", alternativeName: "Skriveblokk", categories: "Generisk", }, { module: Osteotomy, name: "Osteotomy", alternativeName: "Osteotomi", categories: "Samvalg", }, { module: PaintRoller, name: "PaintRoller", alternativeName: "Malingsrull", categories: "Giftinformasjonen", }, { module: PaperPlane, name: "PaperPlane", alternativeName: "Papirfly", categories: "Generisk", }, { module: PatientAndPerson, name: "PatientAndPerson", alternativeName: "", categories: "", }, { module: Pause, name: "Pause", alternativeName: "Pause", categories: "System", }, { module: PdfFile, name: "PdfFile", alternativeName: "PDF", categories: "Filtyper", }, { module: Pencil, name: "Pencil", alternativeName: "Blyant", categories: "Giftinformasjonen", }, { module: PeopleTalking, name: "PeopleTalking", alternativeName: "Samtale", categories: "Samvalg, Personer", }, { module: Peritonealdialysis, name: "Peritonealdialysis", alternativeName: "Peritoneal dialyse", categories: "Samvalg", }, { module: Person, name: "Person", alternativeName: "Person", categories: "Generisk, Personer", }, { module: PersonAndPatient, name: "PersonAndPatient", alternativeName: "Pasient og pårørende", categories: "Behandling, Personer", }, { module: PersonInXRayMachine, name: "PersonInXRayMachine", alternativeName: "Røntgen", categories: "Behandling, Sykdom", }, { module: PersonOverweight, name: "PersonOverweight", alternativeName: "Overvektig person", categories: "Livsstil, Personer", }, { module: PersonRelaxing, name: "PersonRelaxing", alternativeName: "Person som slapper av", categories: "Livsstil, Personer", }, { module: PersonWithBrain, name: "PersonWithBrain", alternativeName: "Person med hjerne", categories: "Anatomi, Personer", }, { module: PersonWithBrokenArm, name: "PersonWithBrokenArm", alternativeName: "Person med brukket arm", categories: "Behandling, Personer", }, { module: PersonWithCrutches, name: "PersonWithCrutches", alternativeName: "Person med krykker", categories: "Behandling, Personer", }, { module: PersonWithJaw, name: "PersonWithJaw", alternativeName: "Person med kjeve", categories: "Anatomi, Personer", }, { module: PersonWithMagnifyingGlass, name: "PersonWithMagnifyingGlass", alternativeName: "Person med lupe", categories: "Behandling, Personer", }, { module: PersonWithSenses, name: "PersonWithSenses", alternativeName: "Person med sanser", categories: "Psykisk helse, Personer", }, { module: PersonWorking, name: "PersonWorking", alternativeName: "Person som jobber", categories: "Generisk, Personer, Samvalg", }, { module: PersonalPlan, name: "PersonalPlan", alternativeName: "Behandlingsplan", categories: "Tjeneste", }, { module: PizzaSlice, name: "PizzaSlice", alternativeName: "Pizza", categories: "Giftinformasjonen, Livsstil", }, { module: Plane, name: "Plane", alternativeName: "Fly", categories: "Kjøretøy", }, { module: Plant, name: "Plant", alternativeName: "Plante", categories: "Giftinformasjonen, Livsstil", }, { module: Play, name: "Play", alternativeName: "Play", categories: "Generisk", }, { module: PlusLarge, name: "PlusLarge", alternativeName: "Stort pluss", categories: "System", }, { module: PlusSmall, name: "PlusSmall", alternativeName: "Liten pluss", categories: "System", }, { module: PngFile, name: "PngFile", alternativeName: "PNG", categories: "Filtyper", }, { module: Podcast, name: "Podcast", alternativeName: "Podcast", categories: "Generisk", }, { module: PoisonInformation, name: "PoisonInformation", alternativeName: "Giftinformasjonen", categories: "Giftinformasjonen", }, { module: Pregnant, name: "Pregnant", alternativeName: "Gravid", categories: "Gravid og fødsel", }, { module: Printer, name: "Printer", alternativeName: "Printer", categories: "Generisk", }, { module: Psychosis, name: "Psychosis", alternativeName: "Psykose", categories: "Sykdom, Psykisk helse", }, { module: Publication, name: "Publication", alternativeName: "Publikasjon", categories: "Generisk", }, { module: Puzzle, name: "Puzzle", alternativeName: "Puslespillbit", categories: "Generisk", }, { module: QrCode, name: "QrCode", alternativeName: "QR kode", categories: "Generisk", }, { module: Quarrel, name: "Quarrel", alternativeName: "Krangle", categories: "Generisk", }, { module: RadioTherapy, name: "RadioTherapy", alternativeName: "Strålebehandling", categories: "Samvalg", }, { module: RadioactiveTreatment, name: "RadioactiveTreatment", alternativeName: "Radioaktiv behandling", categories: "Samvalg", }, { module: Radioiodine, name: "Radioiodine", alternativeName: "Radiojod", categories: "Samvalg", }, { module: Receipt, name: "Receipt", alternativeName: "Kvittering", categories: "Generisk", }, { module: Receptionist, name: "Receptionist", alternativeName: "Person med headset", categories: "Generisk, Personer", }, { module: Recovery, name: "Recovery", alternativeName: "Gjenoppretting", categories: "System, Generisk", }, { module: Referral, name: "Referral", alternativeName: "Henvisninger", categories: "Tjeneste", }, { module: Refresh, name: "Refresh", alternativeName: "Oppdater", categories: "Generisk", }, { module: Refund, name: "Refund", alternativeName: "Refusjon", categories: "Tjeneste", }, { module: Reply, name: "Reply", alternativeName: "Svar", categories: "System", }, { module: Rocket, name: "Rocket", alternativeName: "Romrakett", categories: "Kjøretøy", }, { module: RtfFile, name: "RtfFile", alternativeName: "RTF-fil", categories: "Filtyper", }, { module: STDs, name: "STDs", alternativeName: "Kjønnssykom", categories: "Sykdom, Personer", }, { module: Save, name: "Save", alternativeName: "Lagre", categories: "System", }, { module: Scale, name: "Scale", alternativeName: "Vektskål", categories: "Generisk", }, { module: Search, name: "Search", alternativeName: "Søk", categories: "Generisk", }, { module: SectionSign, name: "SectionSign", alternativeName: "Paragraftegn", categories: "Samvalg, Generisk", }, { module: Settings, name: "Settings", alternativeName: "Innstillinger", categories: "System", }, { module: Sexualorientation, name: "Sexualorientation", alternativeName: "Seksuell orientering", categories: "Generisk", }, { module: ShakingHand, name: "ShakingHand", alternativeName: "Hender som holder", categories: "Tjeneste, Samvalg", }, { module: Share, name: "Share", alternativeName: "Dele", categories: "Sosiale medier", }, { module: Shield, name: "Shield", alternativeName: "Skjold", categories: "System, Generisk", }, { module: ShuntOperation, name: "ShuntOperation", alternativeName: "Shunt-operasjon", categories: "Samvalg", }, { module: Skeleton, name: "Skeleton", alternativeName: "Skjelett", categories: "Sykdom, Anatomi", }, { module: Skin, name: "Skin", alternativeName: "Hud og hår", categories: "Sykdom, Anatomi", }, { module: Snake, name: "Snake", alternativeName: "Slange", categories: "Giftinformasjonen", }, { module: Snapchat, name: "Snapchat", alternativeName: "Snapshat", categories: "Sosiale medier, Generisk", }, { module: SortDown, name: "SortDown", alternativeName: "Sortere ned", categories: "System", }, { module: SortUp, name: "SortUp", alternativeName: "Sortere opp", categories: "System", }, { module: SpeechBubble, name: "SpeechBubble", alternativeName: "Snakkeboble", categories: "Samvalg, Generisk", }, { module: Spray, name: "Spray", alternativeName: "Sprayflaske", categories: "Giftinformasjonen, Livsstil", }, { module: Stopwatch, name: "Stopwatch", alternativeName: "Stoppeklokke", categories: "Generisk", }, { module: SupportingPerson, name: "SupportingPerson", alternativeName: "Ledsager", categories: "Samvalg, Personer", }, { module: Surgery, name: "Surgery", alternativeName: "Kirurgi", categories: "Samvalg, Behandling", }, { module: Syringe, name: "Syringe", alternativeName: "Sprøyte", categories: "Samvalg, Generisk", }, { module: Taxi, name: "Taxi", alternativeName: "Taxi", categories: "Kjøretøy", }, { module: TeddyBear, name: "TeddyBear", alternativeName: "Teddybjørn", categories: "Generisk, Sykdom", }, { module: Teenagers, name: "Teenagers", alternativeName: "Tenåringer", categories: "Generisk, Personer", }, { module: ThinkingAboutBaby, name: "ThinkingAboutBaby", alternativeName: "Ufrivillig barnløshet", categories: "Behandling, Sykdom", }, { module: Ticket, name: "Ticket", alternativeName: "Billett", categories: "Generisk", }, { module: TimePassing, name: "TimePassing", alternativeName: "Tiden går", categories: "Samvalg", }, { module: Toolbox, name: "Toolbox", alternativeName: "Verktøykasse", categories: "Tjeneste, Generisk", }, { module: Tooth, name: "Tooth", alternativeName: "Tann", categories: "Anatomi", }, { module: TotalKneeProsthesis, name: "TotalKneeProsthesis", alternativeName: "Full kneprotese", categories: "Samvalg, Behandling", }, { module: Train, name: "Train", alternativeName: "Tog", categories: "Kjøretøy", }, { module: Transplantation, name: "Transplantation", alternativeName: "Transplantasjon", categories: "Samvalg", }, { module: TrashCan, name: "TrashCan", alternativeName: "Søplekasse", categories: "Generisk", }, { module: Twitter, name: "Twitter", alternativeName: "Twitter", categories: "Sosiale medier, Generisk", }, { module: Undo, name: "Undo", alternativeName: "Angre", categories: "System", }, { module: UniProsthesis, name: "UniProsthesis", alternativeName: "Uniprotese", categories: "Samvalg", }, { module: Upload, name: "Upload", alternativeName: "Last opp", categories: "System", }, { module: UserOrganization, name: "UserOrganization", alternativeName: "Pasient- og brukerorganisasjoner", categories: "Generisk, Personer", }, { module: Vaccine, name: "Vaccine", alternativeName: "Vaksiner", categories: "Tjeneste, Behandling", }, { module: VerticalDots, name: "VerticalDots", alternativeName: "Vertikale prikker", categories: "System", }, { module: VideoCamera, name: "VideoCamera", alternativeName: "Videokamera", categories: "Generisk", }, { module: VideoChat, name: "VideoChat", alternativeName: "Video chat", categories: "Tjeneste, Generisk", }, { module: Wallet, name: "Wallet", alternativeName: "Lommebok", categories: "Tjeneste, Generisk", }, { module: Watch, name: "Watch", alternativeName: "Klokke", categories: "Generisk", }, { module: Website, name: "Website", alternativeName: "Nettside", categories: "Generisk", }, { module: Wheelchair, name: "Wheelchair", alternativeName: "Rullestol", categories: "Generisk, Behandling", }, { module: WheelchairActive, name: "WheelchairActive", alternativeName: "Rullestol aktov", categories: "Generisk, Personer", }, { module: Window, name: "Window", alternativeName: "Vindu", categories: "Generisk", }, { module: WordDocument, name: "WordDocument", alternativeName: "Word fil", categories: "Filtyper", }, { module: WorkSuitcase, name: "WorkSuitcase", alternativeName: "Koffert", categories: "Generisk", }, { module: X, name: "X", alternativeName: "X", categories: "System", }, { module: XOutline, name: "XOutline", alternativeName: "X", categories: "System, Generisk", }, { module: XmlFile, name: "XmlFile", alternativeName: "XML", categories: "Filtyper", }, { module: YouTube, name: "YouTube", alternativeName: "Youtube", categories: "Sosiale medier, Generisk", }, { module: Zoom, name: "Zoom", alternativeName: "Zoom inn", categories: "System, Generisk", }];