/* eslint:disable */
/*
 * This file is automatically generated by SOT
 *
 * This file is for typings support only, it will not supply the actual text, you will still need to download the correct culture spesific .resx file.
 */
export type HNDesignsystemLightBox = {
  /**
   * Lukk lightbox
   */
  ariaLabelCloseButton: string;
  /**
   * Forrige bilde
   */
  ariaLabelLeftArrow: string;
  /**
   * Bildevisning
   */
  ariaLabelLightBox: string;
  /**
   * Neste bilde
   */
  ariaLabelRightArrow: string;
  /**
   * Lukk tekstboks
   */
  ariaLabelCloseTextBox: string;
  /**
   * Åpne tekstboks
   */
  ariaLabelOpenTextBox: string;
  /**
   * Zoom inn
   */
  ariaLabelZoomIn: string;
  /**
   * Zoom ut
   */
  ariaLabelZoomOut: string;
  /**
   * Zoom
   */
  ariaLabelZoomSlider: string;
};

/* eslint:enable */
