export type Styles = {
  button: string;
  button__arrow: string;
  'button__arrow--both-icons': string;
  'button__both-icons': string;
  'button__left-icon': string;
  'button__only-icon': string;
  'button__right-icon': string;
  'button__right-unicode-arrow': string;
  button__text: string;
  'button__text--centered': string;
  'button__text--ellipsis': string;
  'button--arrow': string;
  'button--arrow--both-icons': string;
  'button--borderless': string;
  'button--both-icons': string;
  'button--destructive': string;
  'button--large': string;
  'button--left-icon': string;
  'button--normal': string;
  'button--on-dark': string;
  'button--only-icon': string;
  'button--outline': string;
  'button--right-icon': string;
  'button-wrapper': string;
  'button-wrapper--fluid': string;
  diagonal: string;
  diagonal__line: string;
  'diagonal--on-dark': string;
  expander: string;
  expander__button: string;
  expander__button__text: string;
  'expander__button--expanded': string;
  'expander__button--sticky': string;
  expander__content: string;
  'expander__content--banana': string;
  'expander__content--blueberry': string;
  'expander__content--cherry': string;
  'expander__content--expanded': string;
  'expander__content--icon': string;
  'expander__content--kiwi': string;
  'expander__content--large': string;
  'expander__content--nested-line': string;
  'expander__content--neutral': string;
  'expander__content--plum': string;
  'expander__content--small': string;
  'expander__content--white': string;
  expander__icon: string;
  'expander__icon--left': string;
  'expander__icon--right': string;
  expander__trigger: string;
  'expander__trigger--banana': string;
  'expander__trigger--blueberry': string;
  'expander__trigger--cherry': string;
  'expander__trigger--expanded': string;
  'expander__trigger--icon': string;
  'expander__trigger--kiwi': string;
  'expander__trigger--large': string;
  'expander__trigger--neutral': string;
  'expander__trigger--plum': string;
  'expander__trigger--sticky': string;
  'expander__trigger--white': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
