defaults: &defaults
  working_directory: ~/designsystem/

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build library
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - "lib"
            - "package.json"
  test:
    <<: *defaults 
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
  publish-dev:
    <<: *defaults
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish package (dev)
          command: yarn publish:dev


workflows:
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - test:
          filters:
            tags:
              ignore: /.*/
          requires:
            - build
      - publish-dev:
          requires:
            - test
          filters:
            tags:
              only: /^(v0\.0\.1-dev\.)\d+/