defaults: &defaults
  working_directory: ~/designsystem/

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build library
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - "lib"
            - "package.json"
  test:
    <<: *defaults 
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
  publish-dev:
    <<: *defaults
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check for valid tag and publish
          command: |
            #if git describe --exact-match $CIRCLE_SHA1 | grep "^v0.0.1-dev.[0-999]";
            #git describe --exact-match $CIRCLE_SHA1 | grep "^v0.0.1-dev.[0-999]";
            git describe --tags
            # if git log -1 --pretty=%B | grep "^v0.0.1-dev.[0-999]";
            # then
            #   yarn publish:dev
            # else
            #   echo "Not tagged, skipping release"
            # fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
        - build
        - test:
            requires:
              - build
        - publish-dev:
            requires:
              - test