export type Styles = {
  'link-list': string;
  'link-list__anchor': string;
  'link-list__anchor--blueberry': string;
  'link-list__anchor--button': string;
  'link-list__anchor--cherry': string;
  'link-list__anchor--fill': string;
  'link-list__anchor--fill--blueberry': string;
  'link-list__anchor--fill--cherry': string;
  'link-list__anchor--fill--neutral': string;
  'link-list__anchor--fill--white': string;
  'link-list__anchor--fill-negative': string;
  'link-list__anchor--fill-negative--blueberry': string;
  'link-list__anchor--fill-negative--cherry': string;
  'link-list__anchor--fill-negative--neutral': string;
  'link-list__anchor--fill-negative--white': string;
  'link-list__anchor--large': string;
  'link-list__anchor--line--blueberry': string;
  'link-list__anchor--line--cherry': string;
  'link-list__anchor--line--neutral': string;
  'link-list__anchor--line--white': string;
  'link-list__anchor--medium': string;
  'link-list__anchor--neutral': string;
  'link-list__anchor--new': string;
  'link-list__anchor--outline': string;
  'link-list__anchor--outline--blueberry': string;
  'link-list__anchor--outline--cherry': string;
  'link-list__anchor--outline--neutral': string;
  'link-list__anchor--outline--white': string;
  'link-list__anchor--small': string;
  'link-list__anchor--white': string;
  'link-list__image-container': string;
  'link-list__list-item--line': string;
  'link-list__list-item--outline': string;
  'link-list__list-item--outline--blueberry': string;
  'link-list__list-item--outline--cherry': string;
  'link-list__list-item--outline--neutral': string;
  'link-list__list-item--outline--white': string;
  'link-list__status-marker': string;
  'link-list__status-marker--new': string;
  'link-list--outline--blueberry': string;
  'link-list--outline--cherry': string;
  'link-list--outline--neutral': string;
  'link-list--outline--white': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
