export type Styles = {
  'datetime-container': string;
  'datetime-container__icon': string;
  panel: string;
  'panel__btn-container': string;
  'panel__btn-container--layout3': string;
  'panel__btn-container--padding-top': string;
  panel__container: string;
  'panel__container--grow': string;
  'panel__container--layout3': string;
  'panel__content-left--flex': string;
  'panel__content-right--layout1': string;
  'panel__content-right--layout2': string;
  'panel__content-right--layout3': string;
  'panel__content-right--layout3a': string;
  'panel__content-right--layout3b': string;
  'panel__content-right--layout3c': string;
  'panel__details-btn': string;
  panel__icon: string;
  'panel__icon--right': string;
  'panel--button': string;
  'panel--clickable': string;
  'panel--draft': string;
  'panel--error': string;
  'panel--fill': string;
  'panel--line': string;
  'panel--new': string;
  'panel--no-top-border': string;
  'panel--selected': string;
  'panel--status': string;
  'panel--stroke': string;
  'panel--white': string;
  'panel--with-icon': string;
  'panel-content-a': string;
  'panel-content-a__title-container': string;
  'panel-content-a--layout3a': string;
  'panel-content-a--layout3b': string;
  'panel-content-a--layout3c': string;
  'panel-content-b': string;
  'panel-content-b--layout1': string;
  'panel-content-b--layout3': string;
  'panel-details': string;
  'panel-details--line': string;
  'panel-details--open': string;
  'panel-details--white': string;
  'panel-details--with-icon': string;
  'panel-wrapper': string;
  'status-message': string;
  'status-message--new': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
