export type Styles = {
  button: string;
  button__arrow: string;
  'button__arrow--both-icons': string;
  'button__both-icons': string;
  'button__left-icon': string;
  'button__only-icon': string;
  'button__right-icon': string;
  'button__right-unicode-arrow': string;
  button__text: string;
  'button__text--centered': string;
  'button__text--ellipsis': string;
  'button--arrow': string;
  'button--arrow--both-icons': string;
  'button--borderless': string;
  'button--both-icons': string;
  'button--destructive': string;
  'button--large': string;
  'button--left-icon': string;
  'button--normal': string;
  'button--on-dark': string;
  'button--only-icon': string;
  'button--outline': string;
  'button--right-icon': string;
  'button-wrapper': string;
  'button-wrapper--fluid': string;
  diagonal: string;
  diagonal__line: string;
  'diagonal--on-dark': string;
  panel: string;
  'panel__border--line': string;
  'panel__border--outline': string;
  panel__content: string;
  panel__content__item: string;
  'panel__content__item--a': string;
  'panel__content__item--b': string;
  'panel__content__item--c': string;
  'panel__content--b-first': string;
  'panel__content--bAsRightCol': string;
  'panel__content--combined': string;
  'panel__content--horizontal': string;
  'panel__content--vertical': string;
  panel__expander: string;
  'panel__expander__border--blueberry': string;
  'panel__expander__border--expanded': string;
  'panel__expander__border--neutral': string;
  'panel__expander__border--white': string;
  panel__expander__content: string;
  panel__expander__separator: string;
  'panel__expander--blueberry': string;
  'panel__expander--neutral': string;
  'panel__expander--white': string;
  'panel__pre-container': string;
  'panel--blueberry': string;
  'panel--blueberry--hover': string;
  'panel--border': string;
  'panel--draft': string;
  'panel--error': string;
  'panel--fill': string;
  'panel--icon': string;
  'panel--line': string;
  'panel--neutral': string;
  'panel--neutral--hover': string;
  'panel--new': string;
  'panel--status': string;
  'panel--white': string;
  'panel--white--hover': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
