trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - npm

pool:
  name: Helsenorge_LinuxScaleSetAgents

variables:
  - name: node_version
    value: 22
  - name: HUSKY
    value: 0
  - name: branchName
    value: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  - name: accountName
    value: frankensteinstorybook
  - name: container
    value: $web

stages:
  - stage:
    displayName: Deploy Storybook
    jobs:
      - job:
        displayName: Deploy Storybook
        steps:
          - task: UseNode@1
            displayName: Use Node version
            inputs:
              version: $(node_version)

          - task: Npm@1
            displayName: Install dependencies
            inputs:
              command: ci

          - task: Npm@1
            displayName: Build frankenstein-build-tools
            inputs:
              command: custom
              workingDir: npm/build-tools
              customCommand: run build

          - task: Npm@1
            displayName: Build Storybook
            inputs:
              command: custom
              workingDir: npm/designsystem
              customCommand: run build-storybook -- -o dist/$(branchName) -- --base /$(branchName)/

          - task: AzureCLI@2
            displayName: Copy to Azure Storage account
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob delete-batch --account-name $(accountName) --source '$(container)' --pattern "$(branchName)/*"
                az storage blob upload-batch --account-name $(accountName) --destination '$(container)' --destination-path $(branchName) --source npm/designsystem/dist/$(branchName)
