import AlarmClock_ from '@helsenorge/designsystem-react/components/Icons/AlarmClock';
export const AlarmClock = AlarmClock_;
import AlertSignFill_ from '@helsenorge/designsystem-react/components/Icons/AlertSignFill';
export const AlertSignFill = AlertSignFill_;
import AlertSignStroke_ from '@helsenorge/designsystem-react/components/Icons/AlertSignStroke';
export const AlertSignStroke = AlertSignStroke_;
import Amputation_ from '@helsenorge/designsystem-react/components/Icons/Amputation';
export const Amputation = Amputation_;
import Anxiety_ from '@helsenorge/designsystem-react/components/Icons/Anxiety';
export const Anxiety = Anxiety_;
import Apple_ from '@helsenorge/designsystem-react/components/Icons/Apple';
export const Apple = Apple_;
import Archive_ from '@helsenorge/designsystem-react/components/Icons/Archive';
export const Archive = Archive_;
import ArmFlexing_ from '@helsenorge/designsystem-react/components/Icons/ArmFlexing';
export const ArmFlexing = ArmFlexing_;
import ArrowLeft_ from '@helsenorge/designsystem-react/components/Icons/ArrowLeft';
export const ArrowLeft = ArrowLeft_;
import ArrowRight_ from '@helsenorge/designsystem-react/components/Icons/ArrowRight';
export const ArrowRight = ArrowRight_;
import ArrowUpRight_ from '@helsenorge/designsystem-react/components/Icons/ArrowUpRight';
export const ArrowUpRight = ArrowUpRight_;
import Attachment_ from '@helsenorge/designsystem-react/components/Icons/Attachment';
export const Attachment = Attachment_;
import Atv_ from '@helsenorge/designsystem-react/components/Icons/Atv';
export const Atv = Atv_;
import Avatar_ from '@helsenorge/designsystem-react/components/Icons/Avatar';
export const Avatar = Avatar_;
import AwakePersonOnPillow_ from '@helsenorge/designsystem-react/components/Icons/AwakePersonOnPillow';
export const AwakePersonOnPillow = AwakePersonOnPillow_;
import Baby_ from '@helsenorge/designsystem-react/components/Icons/Baby';
export const Baby = Baby_;
import BandAid_ from '@helsenorge/designsystem-react/components/Icons/BandAid';
export const BandAid = BandAid_;
import BeerAndPills_ from '@helsenorge/designsystem-react/components/Icons/BeerAndPills';
export const BeerAndPills = BeerAndPills_;
import Bell_ from '@helsenorge/designsystem-react/components/Icons/Bell';
export const Bell = Bell_;
import Bike_ from '@helsenorge/designsystem-react/components/Icons/Bike';
export const Bike = Bike_;
import BirthdayCake_ from '@helsenorge/designsystem-react/components/Icons/BirthdayCake';
export const BirthdayCake = BirthdayCake_;
import Boat_ from '@helsenorge/designsystem-react/components/Icons/Boat';
export const Boat = Boat_;
import Brain_ from '@helsenorge/designsystem-react/components/Icons/Brain';
export const Brain = Brain_;
import Breasts_ from '@helsenorge/designsystem-react/components/Icons/Breasts';
export const Breasts = Breasts_;
import BrokenHeart_ from '@helsenorge/designsystem-react/components/Icons/BrokenHeart';
export const BrokenHeart = BrokenHeart_;
import BrokenPuzzle_ from '@helsenorge/designsystem-react/components/Icons/BrokenPuzzle';
export const BrokenPuzzle = BrokenPuzzle_;
import Bus_ from '@helsenorge/designsystem-react/components/Icons/Bus';
export const Bus = Bus_;
import Calendar_ from '@helsenorge/designsystem-react/components/Icons/Calendar';
export const Calendar = Calendar_;
import CalendarEvent_ from '@helsenorge/designsystem-react/components/Icons/CalendarEvent';
export const CalendarEvent = CalendarEvent_;
import CalendarSave_ from '@helsenorge/designsystem-react/components/Icons/CalendarSave';
export const CalendarSave = CalendarSave_;
import Cancer_ from '@helsenorge/designsystem-react/components/Icons/Cancer';
export const Cancer = Cancer_;
import Car_ from '@helsenorge/designsystem-react/components/Icons/Car';
export const Car = Car_;
import Check_ from '@helsenorge/designsystem-react/components/Icons/Check';
export const Check = Check_;
import Chest_ from '@helsenorge/designsystem-react/components/Icons/Chest';
export const Chest = Chest_;
import ChevronDown_ from '@helsenorge/designsystem-react/components/Icons/ChevronDown';
export const ChevronDown = ChevronDown_;
import ChevronLeft_ from '@helsenorge/designsystem-react/components/Icons/ChevronLeft';
export const ChevronLeft = ChevronLeft_;
import ChevronRight_ from '@helsenorge/designsystem-react/components/Icons/ChevronRight';
export const ChevronRight = ChevronRight_;
import ChevronUp_ from '@helsenorge/designsystem-react/components/Icons/ChevronUp';
export const ChevronUp = ChevronUp_;
import ChildPlaying_ from '@helsenorge/designsystem-react/components/Icons/ChildPlaying';
export const ChildPlaying = ChildPlaying_;
import Cigarette_ from '@helsenorge/designsystem-react/components/Icons/Cigarette';
export const Cigarette = Cigarette_;
import Contacts_ from '@helsenorge/designsystem-react/components/Icons/Contacts';
export const Contacts = Contacts_;
import Copy_ from '@helsenorge/designsystem-react/components/Icons/Copy';
export const Copy = Copy_;
import Coronavirus_ from '@helsenorge/designsystem-react/components/Icons/Coronavirus';
export const Coronavirus = Coronavirus_;
import Cough_ from '@helsenorge/designsystem-react/components/Icons/Cough';
export const Cough = Cough_;
import CriticalHealthInfo_ from '@helsenorge/designsystem-react/components/Icons/CriticalHealthInfo';
export const CriticalHealthInfo = CriticalHealthInfo_;
import Cross_ from '@helsenorge/designsystem-react/components/Icons/Cross';
export const Cross = Cross_;
import Depression_ from '@helsenorge/designsystem-react/components/Icons/Depression';
export const Depression = Depression_;
import DigestiveSystem_ from '@helsenorge/designsystem-react/components/Icons/DigestiveSystem';
export const DigestiveSystem = DigestiveSystem_;
import Dizzy_ from '@helsenorge/designsystem-react/components/Icons/Dizzy';
export const Dizzy = Dizzy_;
import Documents_ from '@helsenorge/designsystem-react/components/Icons/Documents';
export const Documents = Documents_;
import Dog_ from '@helsenorge/designsystem-react/components/Icons/Dog';
export const Dog = Dog_;
import DonorCard_ from '@helsenorge/designsystem-react/components/Icons/DonorCard';
export const DonorCard = DonorCard_;
import Draft_ from '@helsenorge/designsystem-react/components/Icons/Draft';
export const Draft = Draft_;
import EChat_ from '@helsenorge/designsystem-react/components/Icons/EChat';
export const EChat = EChat_;
import EarNoseThroat_ from '@helsenorge/designsystem-react/components/Icons/EarNoseThroat';
export const EarNoseThroat = EarNoseThroat_;
import ElderlyPerson_ from '@helsenorge/designsystem-react/components/Icons/ElderlyPerson';
export const ElderlyPerson = ElderlyPerson_;
import EnterFullScreen_ from '@helsenorge/designsystem-react/components/Icons/EnterFullScreen';
export const EnterFullScreen = EnterFullScreen_;
import Envelope_ from '@helsenorge/designsystem-react/components/Icons/Envelope';
export const Envelope = Envelope_;
import Epilepsy_ from '@helsenorge/designsystem-react/components/Icons/Epilepsy';
export const Epilepsy = Epilepsy_;
import Eraser_ from '@helsenorge/designsystem-react/components/Icons/Eraser';
export const Eraser = Eraser_;
import ErrorSignFill_ from '@helsenorge/designsystem-react/components/Icons/ErrorSignFill';
export const ErrorSignFill = ErrorSignFill_;
import ErrorSignStroke_ from '@helsenorge/designsystem-react/components/Icons/ErrorSignStroke';
export const ErrorSignStroke = ErrorSignStroke_;
import EuropeanHealthCard_ from '@helsenorge/designsystem-react/components/Icons/EuropeanHealthCard';
export const EuropeanHealthCard = EuropeanHealthCard_;
import ExitFullScreen_ from '@helsenorge/designsystem-react/components/Icons/ExitFullScreen';
export const ExitFullScreen = ExitFullScreen_;
import Eye_ from '@helsenorge/designsystem-react/components/Icons/Eye';
export const Eye = Eye_;
import Facebook_ from '@helsenorge/designsystem-react/components/Icons/Facebook';
export const Facebook = Facebook_;
import Female_ from '@helsenorge/designsystem-react/components/Icons/Female';
export const Female = Female_;
import FemaleDoctor_ from '@helsenorge/designsystem-react/components/Icons/FemaleDoctor';
export const FemaleDoctor = FemaleDoctor_;
import Ferry_ from '@helsenorge/designsystem-react/components/Icons/Ferry';
export const Ferry = Ferry_;
import FingerBleed_ from '@helsenorge/designsystem-react/components/Icons/FingerBleed';
export const FingerBleed = FingerBleed_;
import FirstAidKit_ from '@helsenorge/designsystem-react/components/Icons/FirstAidKit';
export const FirstAidKit = FirstAidKit_;
import Football_ from '@helsenorge/designsystem-react/components/Icons/Football';
export const Football = Football_;
import Form_ from '@helsenorge/designsystem-react/components/Icons/Form';
export const Form = Form_;
import Forward_ from '@helsenorge/designsystem-react/components/Icons/Forward';
export const Forward = Forward_;
import Garden_ from '@helsenorge/designsystem-react/components/Icons/Garden';
export const Garden = Garden_;
import GasCan_ from '@helsenorge/designsystem-react/components/Icons/GasCan';
export const GasCan = GasCan_;
import Globe_ from '@helsenorge/designsystem-react/components/Icons/Globe';
export const Globe = Globe_;
import HandWaving_ from '@helsenorge/designsystem-react/components/Icons/HandWaving';
export const HandWaving = HandWaving_;
import HandWithDisease_ from '@helsenorge/designsystem-react/components/Icons/HandWithDisease';
export const HandWithDisease = HandWithDisease_;
import Heart_ from '@helsenorge/designsystem-react/components/Icons/Heart';
export const Heart = Heart_;
import HelpSign_ from '@helsenorge/designsystem-react/components/Icons/HelpSign';
export const HelpSign = HelpSign_;
import Hiker_ from '@helsenorge/designsystem-react/components/Icons/Hiker';
export const Hiker = Hiker_;
import History_ from '@helsenorge/designsystem-react/components/Icons/History';
export const History = History_;
import HivAndAids_ from '@helsenorge/designsystem-react/components/Icons/HivAndAids';
export const HivAndAids = HivAndAids_;
import Hormone_ from '@helsenorge/designsystem-react/components/Icons/Hormone';
export const Hormone = Hormone_;
import Hospital_ from '@helsenorge/designsystem-react/components/Icons/Hospital';
export const Hospital = Hospital_;
import ImgFile_ from '@helsenorge/designsystem-react/components/Icons/ImgFile';
export const ImgFile = ImgFile_;
import Inbox_ from '@helsenorge/designsystem-react/components/Icons/Inbox';
export const Inbox = Inbox_;
import InfoSignFill_ from '@helsenorge/designsystem-react/components/Icons/InfoSignFill';
export const InfoSignFill = InfoSignFill_;
import InfoSignStroke_ from '@helsenorge/designsystem-react/components/Icons/InfoSignStroke';
export const InfoSignStroke = InfoSignStroke_;
import Instagram_ from '@helsenorge/designsystem-react/components/Icons/Instagram';
export const Instagram = Instagram_;
import JointPain_ from '@helsenorge/designsystem-react/components/Icons/JointPain';
export const JointPain = JointPain_;
import Journal_ from '@helsenorge/designsystem-react/components/Icons/Journal';
export const Journal = Journal_;
import JpgFile_ from '@helsenorge/designsystem-react/components/Icons/JpgFile';
export const JpgFile = JpgFile_;
import Kidney_ from '@helsenorge/designsystem-react/components/Icons/Kidney';
export const Kidney = Kidney_;
import Kjernejournal_ from '@helsenorge/designsystem-react/components/Icons/Kjernejournal';
export const Kjernejournal = Kjernejournal_;
import Laboratory_ from '@helsenorge/designsystem-react/components/Icons/Laboratory';
export const Laboratory = Laboratory_;
import LaptopBlog_ from '@helsenorge/designsystem-react/components/Icons/LaptopBlog';
export const LaptopBlog = LaptopBlog_;
import LawBook_ from '@helsenorge/designsystem-react/components/Icons/LawBook';
export const LawBook = LawBook_;
import LightBulb_ from '@helsenorge/designsystem-react/components/Icons/LightBulb';
export const LightBulb = LightBulb_;
import Location_ from '@helsenorge/designsystem-react/components/Icons/Location';
export const Location = Location_;
import Lock_ from '@helsenorge/designsystem-react/components/Icons/Lock';
export const Lock = Lock_;
import Lungs_ from '@helsenorge/designsystem-react/components/Icons/Lungs';
export const Lungs = Lungs_;
import Makeup_ from '@helsenorge/designsystem-react/components/Icons/Makeup';
export const Makeup = Makeup_;
import MaleDoctor_ from '@helsenorge/designsystem-react/components/Icons/MaleDoctor';
export const MaleDoctor = MaleDoctor_;
import MaleDoctorAndPerson_ from '@helsenorge/designsystem-react/components/Icons/MaleDoctorAndPerson';
export const MaleDoctorAndPerson = MaleDoctorAndPerson_;
import MaleGenitalia_ from '@helsenorge/designsystem-react/components/Icons/MaleGenitalia';
export const MaleGenitalia = MaleGenitalia_;
import Medicine_ from '@helsenorge/designsystem-react/components/Icons/Medicine';
export const Medicine = Medicine_;
import MedicineWarning_ from '@helsenorge/designsystem-react/components/Icons/MedicineWarning';
export const MedicineWarning = MedicineWarning_;
import MentalHealthAdult_ from '@helsenorge/designsystem-react/components/Icons/MentalHealthAdult';
export const MentalHealthAdult = MentalHealthAdult_;
import MentalHealthChild_ from '@helsenorge/designsystem-react/components/Icons/MentalHealthChild';
export const MentalHealthChild = MentalHealthChild_;
import Menu_ from '@helsenorge/designsystem-react/components/Icons/Menu';
export const Menu = Menu_;
import Microscope_ from '@helsenorge/designsystem-react/components/Icons/Microscope';
export const Microscope = Microscope_;
import Minus_ from '@helsenorge/designsystem-react/components/Icons/Minus';
export const Minus = Minus_;
import Mirror_ from '@helsenorge/designsystem-react/components/Icons/Mirror';
export const Mirror = Mirror_;
import MobilePhone_ from '@helsenorge/designsystem-react/components/Icons/MobilePhone';
export const MobilePhone = MobilePhone_;
import MotherHoldingBaby_ from '@helsenorge/designsystem-react/components/Icons/MotherHoldingBaby';
export const MotherHoldingBaby = MotherHoldingBaby_;
import MuscleBack_ from '@helsenorge/designsystem-react/components/Icons/MuscleBack';
export const MuscleBack = MuscleBack_;
import MuscleLeg_ from '@helsenorge/designsystem-react/components/Icons/MuscleLeg';
export const MuscleLeg = MuscleLeg_;
import Mushroom_ from '@helsenorge/designsystem-react/components/Icons/Mushroom';
export const Mushroom = Mushroom_;
import MusselsAndSalt_ from '@helsenorge/designsystem-react/components/Icons/MusselsAndSalt';
export const MusselsAndSalt = MusselsAndSalt_;
import NoFilter_ from '@helsenorge/designsystem-react/components/Icons/NoFilter';
export const NoFilter = NoFilter_;
import Notepad_ from '@helsenorge/designsystem-react/components/Icons/Notepad';
export const Notepad = Notepad_;
import PaintRoller_ from '@helsenorge/designsystem-react/components/Icons/PaintRoller';
export const PaintRoller = PaintRoller_;
import PaperPlane_ from '@helsenorge/designsystem-react/components/Icons/PaperPlane';
export const PaperPlane = PaperPlane_;
import PatientAndPerson_ from '@helsenorge/designsystem-react/components/Icons/PatientAndPerson';
export const PatientAndPerson = PatientAndPerson_;
import Pause_ from '@helsenorge/designsystem-react/components/Icons/Pause';
export const Pause = Pause_;
import PdfFile_ from '@helsenorge/designsystem-react/components/Icons/PdfFile';
export const PdfFile = PdfFile_;
import Pencil_ from '@helsenorge/designsystem-react/components/Icons/Pencil';
export const Pencil = Pencil_;
import Person_ from '@helsenorge/designsystem-react/components/Icons/Person';
export const Person = Person_;
import PersonAndPatient_ from '@helsenorge/designsystem-react/components/Icons/PersonAndPatient';
export const PersonAndPatient = PersonAndPatient_;
import PersonInXRayMachine_ from '@helsenorge/designsystem-react/components/Icons/PersonInXRayMachine';
export const PersonInXRayMachine = PersonInXRayMachine_;
import PersonOverweight_ from '@helsenorge/designsystem-react/components/Icons/PersonOverweight';
export const PersonOverweight = PersonOverweight_;
import PersonRelaxing_ from '@helsenorge/designsystem-react/components/Icons/PersonRelaxing';
export const PersonRelaxing = PersonRelaxing_;
import PersonWithBrain_ from '@helsenorge/designsystem-react/components/Icons/PersonWithBrain';
export const PersonWithBrain = PersonWithBrain_;
import PersonWithBrokenArm_ from '@helsenorge/designsystem-react/components/Icons/PersonWithBrokenArm';
export const PersonWithBrokenArm = PersonWithBrokenArm_;
import PersonWithCrutches_ from '@helsenorge/designsystem-react/components/Icons/PersonWithCrutches';
export const PersonWithCrutches = PersonWithCrutches_;
import PersonWithJaw_ from '@helsenorge/designsystem-react/components/Icons/PersonWithJaw';
export const PersonWithJaw = PersonWithJaw_;
import PersonWithMagnifyingGlass_ from '@helsenorge/designsystem-react/components/Icons/PersonWithMagnifyingGlass';
export const PersonWithMagnifyingGlass = PersonWithMagnifyingGlass_;
import PersonWithSenses_ from '@helsenorge/designsystem-react/components/Icons/PersonWithSenses';
export const PersonWithSenses = PersonWithSenses_;
import PersonWorking_ from '@helsenorge/designsystem-react/components/Icons/PersonWorking';
export const PersonWorking = PersonWorking_;
import PizzaSlice_ from '@helsenorge/designsystem-react/components/Icons/PizzaSlice';
export const PizzaSlice = PizzaSlice_;
import Plane_ from '@helsenorge/designsystem-react/components/Icons/Plane';
export const Plane = Plane_;
import Plant_ from '@helsenorge/designsystem-react/components/Icons/Plant';
export const Plant = Plant_;
import PlusLarge_ from '@helsenorge/designsystem-react/components/Icons/PlusLarge';
export const PlusLarge = PlusLarge_;
import PlusSmall_ from '@helsenorge/designsystem-react/components/Icons/PlusSmall';
export const PlusSmall = PlusSmall_;
import PngFile_ from '@helsenorge/designsystem-react/components/Icons/PngFile';
export const PngFile = PngFile_;
import PoisonInformation_ from '@helsenorge/designsystem-react/components/Icons/PoisonInformation';
export const PoisonInformation = PoisonInformation_;
import Pregnant_ from '@helsenorge/designsystem-react/components/Icons/Pregnant';
export const Pregnant = Pregnant_;
import Printer_ from '@helsenorge/designsystem-react/components/Icons/Printer';
export const Printer = Printer_;
import Psychosis_ from '@helsenorge/designsystem-react/components/Icons/Psychosis';
export const Psychosis = Psychosis_;
import Publication_ from '@helsenorge/designsystem-react/components/Icons/Publication';
export const Publication = Publication_;
import Puzzle_ from '@helsenorge/designsystem-react/components/Icons/Puzzle';
export const Puzzle = Puzzle_;
import Receipt_ from '@helsenorge/designsystem-react/components/Icons/Receipt';
export const Receipt = Receipt_;
import Receptionist_ from '@helsenorge/designsystem-react/components/Icons/Receptionist';
export const Receptionist = Receptionist_;
import Referral_ from '@helsenorge/designsystem-react/components/Icons/Referral';
export const Referral = Referral_;
import Refresh_ from '@helsenorge/designsystem-react/components/Icons/Refresh';
export const Refresh = Refresh_;
import Refund_ from '@helsenorge/designsystem-react/components/Icons/Refund';
export const Refund = Refund_;
import Reply_ from '@helsenorge/designsystem-react/components/Icons/Reply';
export const Reply = Reply_;
import Rocket_ from '@helsenorge/designsystem-react/components/Icons/Rocket';
export const Rocket = Rocket_;
import RtfFile_ from '@helsenorge/designsystem-react/components/Icons/RtfFile';
export const RtfFile = RtfFile_;
import Save_ from '@helsenorge/designsystem-react/components/Icons/Save';
export const Save = Save_;
import Scale_ from '@helsenorge/designsystem-react/components/Icons/Scale';
export const Scale = Scale_;
import Search_ from '@helsenorge/designsystem-react/components/Icons/Search';
export const Search = Search_;
import ShakingHand_ from '@helsenorge/designsystem-react/components/Icons/ShakingHand';
export const ShakingHand = ShakingHand_;
import Share_ from '@helsenorge/designsystem-react/components/Icons/Share';
export const Share = Share_;
import Skeleton_ from '@helsenorge/designsystem-react/components/Icons/Skeleton';
export const Skeleton = Skeleton_;
import Skin_ from '@helsenorge/designsystem-react/components/Icons/Skin';
export const Skin = Skin_;
import Snake_ from '@helsenorge/designsystem-react/components/Icons/Snake';
export const Snake = Snake_;
import Snapchat_ from '@helsenorge/designsystem-react/components/Icons/Snapchat';
export const Snapchat = Snapchat_;
import Spray_ from '@helsenorge/designsystem-react/components/Icons/Spray';
export const Spray = Spray_;
import Taxi_ from '@helsenorge/designsystem-react/components/Icons/Taxi';
export const Taxi = Taxi_;
import TeddyBear_ from '@helsenorge/designsystem-react/components/Icons/TeddyBear';
export const TeddyBear = TeddyBear_;
import ThinkingAboutBaby_ from '@helsenorge/designsystem-react/components/Icons/ThinkingAboutBaby';
export const ThinkingAboutBaby = ThinkingAboutBaby_;
import Ticket_ from '@helsenorge/designsystem-react/components/Icons/Ticket';
export const Ticket = Ticket_;
import Toolbox_ from '@helsenorge/designsystem-react/components/Icons/Toolbox';
export const Toolbox = Toolbox_;
import Tooth_ from '@helsenorge/designsystem-react/components/Icons/Tooth';
export const Tooth = Tooth_;
import Train_ from '@helsenorge/designsystem-react/components/Icons/Train';
export const Train = Train_;
import TrashCan_ from '@helsenorge/designsystem-react/components/Icons/TrashCan';
export const TrashCan = TrashCan_;
import Twitter_ from '@helsenorge/designsystem-react/components/Icons/Twitter';
export const Twitter = Twitter_;
import Upload_ from '@helsenorge/designsystem-react/components/Icons/Upload';
export const Upload = Upload_;
import UserOrganization_ from '@helsenorge/designsystem-react/components/Icons/UserOrganization';
export const UserOrganization = UserOrganization_;
import Vaccine_ from '@helsenorge/designsystem-react/components/Icons/Vaccine';
export const Vaccine = Vaccine_;
import VerticalDots_ from '@helsenorge/designsystem-react/components/Icons/VerticalDots';
export const VerticalDots = VerticalDots_;
import VideoCamera_ from '@helsenorge/designsystem-react/components/Icons/VideoCamera';
export const VideoCamera = VideoCamera_;
import VideoChat_ from '@helsenorge/designsystem-react/components/Icons/VideoChat';
export const VideoChat = VideoChat_;
import Wallet_ from '@helsenorge/designsystem-react/components/Icons/Wallet';
export const Wallet = Wallet_;
import Window_ from '@helsenorge/designsystem-react/components/Icons/Window';
export const Window = Window_;
import WordDocument_ from '@helsenorge/designsystem-react/components/Icons/WordDocument';
export const WordDocument = WordDocument_;
import WorkSuitcase_ from '@helsenorge/designsystem-react/components/Icons/WorkSuitcase';
export const WorkSuitcase = WorkSuitcase_;
import X_ from '@helsenorge/designsystem-react/components/Icons/X';
export const X = X_;
import XmlFile_ from '@helsenorge/designsystem-react/components/Icons/XmlFile';
export const XmlFile = XmlFile_;
import YouTube_ from '@helsenorge/designsystem-react/components/Icons/YouTube';
export const YouTube = YouTube_;


export const allSvgIcons = [ { "module": AlarmClock, "name": "AlarmClock"}, { "module": AlertSignFill, "name": "AlertSignFill"}, { "module": AlertSignStroke, "name": "AlertSignStroke"}, { "module": Amputation, "name": "Amputation"}, { "module": Anxiety, "name": "Anxiety"}, { "module": Apple, "name": "Apple"}, { "module": Archive, "name": "Archive"}, { "module": ArmFlexing, "name": "ArmFlexing"}, { "module": ArrowLeft, "name": "ArrowLeft"}, { "module": ArrowRight, "name": "ArrowRight"}, { "module": ArrowUpRight, "name": "ArrowUpRight"}, { "module": Attachment, "name": "Attachment"}, { "module": Atv, "name": "Atv"}, { "module": Avatar, "name": "Avatar"}, { "module": AwakePersonOnPillow, "name": "AwakePersonOnPillow"}, { "module": Baby, "name": "Baby"}, { "module": BandAid, "name": "BandAid"}, { "module": BeerAndPills, "name": "BeerAndPills"}, { "module": Bell, "name": "Bell"}, { "module": Bike, "name": "Bike"}, { "module": BirthdayCake, "name": "BirthdayCake"}, { "module": Boat, "name": "Boat"}, { "module": Brain, "name": "Brain"}, { "module": Breasts, "name": "Breasts"}, { "module": BrokenHeart, "name": "BrokenHeart"}, { "module": BrokenPuzzle, "name": "BrokenPuzzle"}, { "module": Bus, "name": "Bus"}, { "module": Calendar, "name": "Calendar"}, { "module": CalendarEvent, "name": "CalendarEvent"}, { "module": CalendarSave, "name": "CalendarSave"}, { "module": Cancer, "name": "Cancer"}, { "module": Car, "name": "Car"}, { "module": Check, "name": "Check"}, { "module": Chest, "name": "Chest"}, { "module": ChevronDown, "name": "ChevronDown"}, { "module": ChevronLeft, "name": "ChevronLeft"}, { "module": ChevronRight, "name": "ChevronRight"}, { "module": ChevronUp, "name": "ChevronUp"}, { "module": ChildPlaying, "name": "ChildPlaying"}, { "module": Cigarette, "name": "Cigarette"}, { "module": Contacts, "name": "Contacts"}, { "module": Copy, "name": "Copy"}, { "module": Coronavirus, "name": "Coronavirus"}, { "module": Cough, "name": "Cough"}, { "module": CriticalHealthInfo, "name": "CriticalHealthInfo"}, { "module": Cross, "name": "Cross"}, { "module": Depression, "name": "Depression"}, { "module": DigestiveSystem, "name": "DigestiveSystem"}, { "module": Dizzy, "name": "Dizzy"}, { "module": Documents, "name": "Documents"}, { "module": Dog, "name": "Dog"}, { "module": DonorCard, "name": "DonorCard"}, { "module": Draft, "name": "Draft"}, { "module": EChat, "name": "EChat"}, { "module": EarNoseThroat, "name": "EarNoseThroat"}, { "module": ElderlyPerson, "name": "ElderlyPerson"}, { "module": EnterFullScreen, "name": "EnterFullScreen"}, { "module": Envelope, "name": "Envelope"}, { "module": Epilepsy, "name": "Epilepsy"}, { "module": Eraser, "name": "Eraser"}, { "module": ErrorSignFill, "name": "ErrorSignFill"}, { "module": ErrorSignStroke, "name": "ErrorSignStroke"}, { "module": EuropeanHealthCard, "name": "EuropeanHealthCard"}, { "module": ExitFullScreen, "name": "ExitFullScreen"}, { "module": Eye, "name": "Eye"}, { "module": Facebook, "name": "Facebook"}, { "module": Female, "name": "Female"}, { "module": FemaleDoctor, "name": "FemaleDoctor"}, { "module": Ferry, "name": "Ferry"}, { "module": FingerBleed, "name": "FingerBleed"}, { "module": FirstAidKit, "name": "FirstAidKit"}, { "module": Football, "name": "Football"}, { "module": Form, "name": "Form"}, { "module": Forward, "name": "Forward"}, { "module": Garden, "name": "Garden"}, { "module": GasCan, "name": "GasCan"}, { "module": Globe, "name": "Globe"}, { "module": HandWaving, "name": "HandWaving"}, { "module": HandWithDisease, "name": "HandWithDisease"}, { "module": Heart, "name": "Heart"}, { "module": HelpSign, "name": "HelpSign"}, { "module": Hiker, "name": "Hiker"}, { "module": History, "name": "History"}, { "module": HivAndAids, "name": "HivAndAids"}, { "module": Hormone, "name": "Hormone"}, { "module": Hospital, "name": "Hospital"}, { "module": ImgFile, "name": "ImgFile"}, { "module": Inbox, "name": "Inbox"}, { "module": InfoSignFill, "name": "InfoSignFill"}, { "module": InfoSignStroke, "name": "InfoSignStroke"}, { "module": Instagram, "name": "Instagram"}, { "module": JointPain, "name": "JointPain"}, { "module": Journal, "name": "Journal"}, { "module": JpgFile, "name": "JpgFile"}, { "module": Kidney, "name": "Kidney"}, { "module": Kjernejournal, "name": "Kjernejournal"}, { "module": Laboratory, "name": "Laboratory"}, { "module": LaptopBlog, "name": "LaptopBlog"}, { "module": LawBook, "name": "LawBook"}, { "module": LightBulb, "name": "LightBulb"}, { "module": Location, "name": "Location"}, { "module": Lock, "name": "Lock"}, { "module": Lungs, "name": "Lungs"}, { "module": Makeup, "name": "Makeup"}, { "module": MaleDoctor, "name": "MaleDoctor"}, { "module": MaleDoctorAndPerson, "name": "MaleDoctorAndPerson"}, { "module": MaleGenitalia, "name": "MaleGenitalia"}, { "module": Medicine, "name": "Medicine"}, { "module": MedicineWarning, "name": "MedicineWarning"}, { "module": MentalHealthAdult, "name": "MentalHealthAdult"}, { "module": MentalHealthChild, "name": "MentalHealthChild"}, { "module": Menu, "name": "Menu"}, { "module": Microscope, "name": "Microscope"}, { "module": Minus, "name": "Minus"}, { "module": Mirror, "name": "Mirror"}, { "module": MobilePhone, "name": "MobilePhone"}, { "module": MotherHoldingBaby, "name": "MotherHoldingBaby"}, { "module": MuscleBack, "name": "MuscleBack"}, { "module": MuscleLeg, "name": "MuscleLeg"}, { "module": Mushroom, "name": "Mushroom"}, { "module": MusselsAndSalt, "name": "MusselsAndSalt"}, { "module": NoFilter, "name": "NoFilter"}, { "module": Notepad, "name": "Notepad"}, { "module": PaintRoller, "name": "PaintRoller"}, { "module": PaperPlane, "name": "PaperPlane"}, { "module": PatientAndPerson, "name": "PatientAndPerson"}, { "module": Pause, "name": "Pause"}, { "module": PdfFile, "name": "PdfFile"}, { "module": Pencil, "name": "Pencil"}, { "module": Person, "name": "Person"}, { "module": PersonAndPatient, "name": "PersonAndPatient"}, { "module": PersonInXRayMachine, "name": "PersonInXRayMachine"}, { "module": PersonOverweight, "name": "PersonOverweight"}, { "module": PersonRelaxing, "name": "PersonRelaxing"}, { "module": PersonWithBrain, "name": "PersonWithBrain"}, { "module": PersonWithBrokenArm, "name": "PersonWithBrokenArm"}, { "module": PersonWithCrutches, "name": "PersonWithCrutches"}, { "module": PersonWithJaw, "name": "PersonWithJaw"}, { "module": PersonWithMagnifyingGlass, "name": "PersonWithMagnifyingGlass"}, { "module": PersonWithSenses, "name": "PersonWithSenses"}, { "module": PersonWorking, "name": "PersonWorking"}, { "module": PizzaSlice, "name": "PizzaSlice"}, { "module": Plane, "name": "Plane"}, { "module": Plant, "name": "Plant"}, { "module": PlusLarge, "name": "PlusLarge"}, { "module": PlusSmall, "name": "PlusSmall"}, { "module": PngFile, "name": "PngFile"}, { "module": PoisonInformation, "name": "PoisonInformation"}, { "module": Pregnant, "name": "Pregnant"}, { "module": Printer, "name": "Printer"}, { "module": Psychosis, "name": "Psychosis"}, { "module": Publication, "name": "Publication"}, { "module": Puzzle, "name": "Puzzle"}, { "module": Receipt, "name": "Receipt"}, { "module": Receptionist, "name": "Receptionist"}, { "module": Referral, "name": "Referral"}, { "module": Refresh, "name": "Refresh"}, { "module": Refund, "name": "Refund"}, { "module": Reply, "name": "Reply"}, { "module": Rocket, "name": "Rocket"}, { "module": RtfFile, "name": "RtfFile"}, { "module": Save, "name": "Save"}, { "module": Scale, "name": "Scale"}, { "module": Search, "name": "Search"}, { "module": ShakingHand, "name": "ShakingHand"}, { "module": Share, "name": "Share"}, { "module": Skeleton, "name": "Skeleton"}, { "module": Skin, "name": "Skin"}, { "module": Snake, "name": "Snake"}, { "module": Snapchat, "name": "Snapchat"}, { "module": Spray, "name": "Spray"}, { "module": Taxi, "name": "Taxi"}, { "module": TeddyBear, "name": "TeddyBear"}, { "module": ThinkingAboutBaby, "name": "ThinkingAboutBaby"}, { "module": Ticket, "name": "Ticket"}, { "module": Toolbox, "name": "Toolbox"}, { "module": Tooth, "name": "Tooth"}, { "module": Train, "name": "Train"}, { "module": TrashCan, "name": "TrashCan"}, { "module": Twitter, "name": "Twitter"}, { "module": Upload, "name": "Upload"}, { "module": UserOrganization, "name": "UserOrganization"}, { "module": Vaccine, "name": "Vaccine"}, { "module": VerticalDots, "name": "VerticalDots"}, { "module": VideoCamera, "name": "VideoCamera"}, { "module": VideoChat, "name": "VideoChat"}, { "module": Wallet, "name": "Wallet"}, { "module": Window, "name": "Window"}, { "module": WordDocument, "name": "WordDocument"}, { "module": WorkSuitcase, "name": "WorkSuitcase"}, { "module": X, "name": "X"}, { "module": XmlFile, "name": "XmlFile"}, { "module": YouTube, "name": "YouTube"}];