import React from 'react';
import {PaletteNames} from '../../theme/palette';
import {getColor} from '../../theme/currys/color';

/* [START] This is auto-generated by iconGenerator.js */
import AlarmClock from './AlarmClock';
import ArrowLeft from './ArrowLeft';
import ArrowRight from './ArrowRight';
import Avatar from './Avatar';
import CalendarSave from './CalendarSave';
import Check from './Check';
import ChevronDown from './ChevronDown';
import ChevronLeft from './ChevronLeft';
import ChevronRight from './ChevronRight';
import ChevronUp from './ChevronUp';
import Cross from './Cross';
import EnterFullScreen from './EnterFullScreen';
import Eraser from './Eraser';
import ExitFullScreen from './ExitFullScreen';
import Eye from './Eye';
import FilterOff from './FilterOff';
import Forward from './Forward';
import Lock from './Lock';
import Menu from './Menu';
import Minus from './Minus';
import PaperPlane from './PaperPlane';
import Pause from './Pause';
import Pencil from './Pencil';
import PlusLarge from './PlusLarge';
import PlusSmall from './PlusSmall';
import Printer from './Printer';
import Reply from './Reply';
import Search from './Search';
import Share from './Share';
import VerticalDots from './VerticalDots';
import X from './X';
import Archive from './Archive';
import Bus from './Bus';
import CriticalHealthInfo from './CiriticalHealthInfo';
import Contacts from './Contacts';
import Documents from './Documents';
import DonorCard from './DonorCard';
import Calendar from './Calendar';
import Envelope from './Envelope';
import EuropeanHealthCard from './EuropeanHealthCard';
import Hospital from './Hospital';
import Journal from './Journal';
import Kjernejournal from './Kjernejournal';
import Laboratory from './Laboratory';
import MaleDoctor from './MaleDoctor';
import Medicine from './Medicine';
import MedicineWarning from './MedicineWarning';
import Microscope from './Microscope';
import Referral from './Referral';
import Refund from './Refund';
import Scale from './Scale';
import Toolbox from './Toolbox';
import Vaccine from './Vaccine';
import Wallet from './Wallet';

const iconMapping = {
  alarmClock: AlarmClock,
  archive: Archive,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  avatar: Avatar,
  bus: Bus,
  calendar: Calendar,
  calendarSave: CalendarSave,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  criticalHealthInfo: CriticalHealthInfo,
  contacts: Contacts,
  cross: Cross,
  documents: Documents,
  donorCard: DonorCard,
  enterFullScreen: EnterFullScreen,
  envelope: Envelope,
  eraser: Eraser,
  europeanHealthCard: EuropeanHealthCard,
  exitFullScreen: ExitFullScreen,
  eye: Eye,
  filterOff: FilterOff,
  forward: Forward,
  hospital: Hospital,
  journal: Journal,
  kjernejournal: Kjernejournal,
  laboratory: Laboratory,
  lock: Lock,
  maleDoctor: MaleDoctor,
  medicine: Medicine,
  medicineWarning: MedicineWarning,
  menu: Menu,
  microscope: Microscope,
  minus: Minus,
  paperPlane: PaperPlane,
  pause: Pause,
  pencil: Pencil,
  plusLarge: PlusLarge,
  plusSmall: PlusSmall,
  printer: Printer,
  referral: Referral,
  refund: Refund,
  reply: Reply,
  scale: Scale,
  search: Search,
  toolbox: Toolbox,
  vaccine: Vaccine,
  share: Share,
  verticalDots: VerticalDots,
  wallet: Wallet,
  x: X,
};
/* [END] This is auto-generated by iconGenerator.js */

export type IconColors = PaletteNames;
export type IconTypes =
  | 'alarmClock'
  | 'archive'
  | 'arrowLeft'
  | 'arrowRight'
  | 'avatar'
  | 'bus'
  | 'calendar'
  | 'calendarSave'
  | 'check'
  | 'chevronDown'
  | 'chevronLeft'
  | 'chevronRight'
  | 'chevronUp'
  | 'criticalHealthInfo'
  | 'contacts'
  | 'cross'
  | 'documents'
  | 'donorCard'
  | 'enterFullScreen'
  | 'envelope'
  | 'eraser'
  | 'europeanHealthCard'
  | 'exitFullScreen'
  | 'eye'
  | 'filterOff'
  | 'forward'
  | 'hospital'
  | 'journal'
  | 'kjernejournal'
  | 'laboratory'
  | 'lock'
  | 'maleDoctor'
  | 'medicine'
  | 'medicineWarning'
  | 'menu'
  | 'microscope'
  | 'minus'
  | 'paperPlane'
  | 'pause'
  | 'pencil'
  | 'plusLarge'
  | 'plusSmall'
  | 'printer'
  | 'referral'
  | 'refund'
  | 'reply'
  | 'scale'
  | 'search'
  | 'share'
  | 'toolbox'
  | 'vaccine'
  | 'verticalDots'
  | 'wallet'
  | 'x';

interface IconProps {
  type: IconTypes;
  size?: number;
  color?: IconColors;
  isHovered?: boolean;
}

interface IconRawProps {
  color: string;
  hoverColor: string;
  size?: number;
  isHovered?: boolean;
}

const Icon = React.forwardRef((props: IconProps, ref: any) => {
  const {type, size = 38, color = 'black', isHovered = false} = props;
  return React.createElement(iconMapping[type], {
    size,
    color: getColor(color, 600),
    hoverColor: getColor(color, 700),
    isHovered,
    ref: ref,
  });
});

Icon.displayName = 'Icon';

export {Icon, IconProps, IconRawProps};
