/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ActionButtonVariant,
} from '../src/components/action-button/action-button';

export namespace Components {
  interface HndsActionButton {
    'variant': ActionButtonVariant;
  }
}

declare global {


  interface HTMLHndsActionButtonElement extends Components.HndsActionButton, HTMLStencilElement {}
  var HTMLHndsActionButtonElement: {
    prototype: HTMLHndsActionButtonElement;
    new (): HTMLHndsActionButtonElement;
  };
  interface HTMLElementTagNameMap {
    'hnds-action-button': HTMLHndsActionButtonElement;
  }
}

declare namespace LocalJSX {
  interface HndsActionButton extends JSXBase.HTMLAttributes<HTMLHndsActionButtonElement> {
    'variant'?: ActionButtonVariant;
  }

  interface IntrinsicElements {
    'hnds-action-button': HndsActionButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


