export type Styles = {
  'expandable-container': string;
  table: string;
  table__cell: string;
  'table__cell--behind-expander': string;
  'table__cell--center': string;
  'table__cell--compact': string;
  'table__cell--nowrap': string;
  'table__cell--right': string;
  'table__cell--transparent': string;
  'table__cell-content': string;
  'table__cell-expander': string;
  'table__cell-label': string;
  'table__cell-pop-menu': string;
  'table__expanded-row': string;
  'table__expanded-row--expanded': string;
  'table__expanded-row--stack-only': string;
  'table__expanded-row-container': string;
  'table__expanded-row-container--open': string;
  'table__expanded-row-details': string;
  'table__expander-button': string;
  'table__expander-cell-mobile': string;
  'table__expander-cell-mobile--expanded': string;
  'table__expander-trigger': string;
  table__head: string;
  'table__head-cell': string;
  'table__head-cell--compact': string;
  'table__head-cell--transparent': string;
  'table__pop-menu': string;
  table__row: string;
  'table__row--expandable': string;
  'table__row--expanded': string;
  'table--centeredoverflow-lg': string;
  'table--centeredoverflow-md': string;
  'table--centeredoverflow-sm': string;
  'table--centeredoverflow-xl': string;
  'table--centeredoverflow-xs': string;
  'table--centeredoverflow-xxs': string;
  'table--stack-lg': string;
  'table--stack-md': string;
  'table--stack-sm': string;
  'table--stack-xl': string;
  'table--stack-xs': string;
  'table--stack-xxs': string;
  'table-body': string;
  'table-body--zebra': string;
  'table-caption': string;
  'table-row': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
