/* eslint:disable */
/*
 * This file is automatically generated by SOT
 *
 * This file is for typings support only, it will not supply the actual text, you will still need to download the correct culture spesific .resx file.
 */
export type HNDesignsystemDatePicker = {
  /**
   * Åpne datovelger
   */
  dateButtonAriaLabel: string;
  /**
   * {date}
   */
  dayButtonBase: string;
  /**
   * I dag, {date}
   */
  dayButtonToday: string;
  /**
   * {date} valgt
   */
  dayButtonSelected: string;
  /**
   * Neste måned
   */
  nextMonth: string;
  /**
   * Forrige måned
   */
  previousMonth: string;
  /**
   * Velg måned
   */
  monthDropdown: string;
  /**
   * Velg år
   */
  yearDropdown: string;
  /**
   * Gå til i dag
   */
  goToToday: string;
  /**
   * Henter info. \n Vennligst vent.
   */
  loadingText: string;
};

/* eslint:enable */
