name: Build & Test

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Build pattern library
      run: yarn build
    - name: Run tests
      run: yarn test
    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}



