name: Build & Publish (develop)

on:
  push:
    branches: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm i
      - name: Install dependencies i packages
        run: npm run install:packages
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
# Publiserer foreløpig manuelt
#      - name: Publish
#        run: lerna publish from-git --yes --dist-tag dev
#        continue-on-error: true
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}        
