name: Build & Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Build pattern library
        run: yarn build
      - name: Run tests
        run: yarn test
